/**
 * Job-Contract-Tabelle — Checklisten, kein Wortlaut.
 */

import type { FindusJobId, JobContract } from './types';

const C = (
  partial: JobContract,
): JobContract => partial;

export const JOB_CONTRACTS: Record<FindusJobId, JobContract> = {
  nav_route: C({
    id: 'nav_route',
    agentIntent: 'mobility',
    label: 'Navigation / Route',
    speechBudgetChars: 420,
    commitmentDefault: 'committed',
    fastFacts: ['concrete_place', 'route_or_nav'],
    slowFacts: [],
    requiredActions: ['START_NAVIGATION'],
    bridgeMode: 'fact_ack',
  }),
  transit_live: C({
    id: 'transit_live',
    agentIntent: 'mobility',
    label: 'ÖPNV live',
    speechBudgetChars: 520,
    commitmentDefault: 'exploring',
    fastFacts: ['transit_connection', 'concrete_place'],
    slowFacts: ['price_eur', 'alternative_offered'],
    requiredActions: ['START_NAVIGATION', 'SHOW_MORE'],
    bridgeMode: 'fact_ack',
  }),
  mobility_rent: C({
    id: 'mobility_rent',
    agentIntent: 'booking',
    label: 'Leihrad / Scooter / Mietwagen',
    speechBudgetChars: 480,
    commitmentDefault: 'exploring',
    fastFacts: ['concrete_place', 'venue_options'],
    slowFacts: ['price_eur', 'ticket_or_info_url'],
    requiredActions: ['OPEN_URL'],
    bridgeMode: 'motivate',
  }),
  taxi_rideshare: C({
    id: 'taxi_rideshare',
    agentIntent: 'mobility',
    label: 'Taxi / Uber',
    speechBudgetChars: 400,
    commitmentDefault: 'exploring',
    fastFacts: ['concrete_place'],
    slowFacts: ['price_eur'],
    requiredActions: ['BOOK_UBER', 'DIAL_PHONE'],
    bridgeMode: 'fact_ack',
  }),
  parking_ev: C({
    id: 'parking_ev',
    agentIntent: 'mobility',
    label: 'Parken / Laden',
    speechBudgetChars: 450,
    commitmentDefault: 'exploring',
    fastFacts: ['concrete_place'],
    slowFacts: ['price_eur', 'alternative_offered'],
    requiredActions: ['START_NAVIGATION'],
    bridgeMode: 'fact_ack',
  }),
  dining_open: C({
    id: 'dining_open',
    agentIntent: 'gastro',
    label: 'Gastro offen',
    speechBudgetChars: 560,
    commitmentDefault: 'exploring',
    fastFacts: ['venue_options', 'concrete_place'],
    slowFacts: ['price_eur', 'ticket_or_info_url', 'open_now_or_hours'],
    requiredActions: ['OPEN_URL', 'SHOW_MORE'],
    bridgeMode: 'motivate',
  }),
  dining_hard_match: C({
    id: 'dining_hard_match',
    agentIntent: 'gastro',
    label: 'Gastro Hard-Match',
    speechBudgetChars: 580,
    commitmentDefault: 'exploring',
    fastFacts: ['venue_options', 'hard_match_evidence', 'concrete_place'],
    slowFacts: ['price_eur', 'ticket_or_info_url', 'open_now_or_hours'],
    requiredActions: ['OPEN_URL', 'START_NAVIGATION'],
    bridgeMode: 'motivate',
  }),
  stay_search: C({
    id: 'stay_search',
    agentIntent: 'booking',
    label: 'Hotel / Hostel',
    speechBudgetChars: 600,
    commitmentDefault: 'exploring',
    fastFacts: ['venue_options', 'hard_match_evidence'],
    slowFacts: ['price_eur', 'booking_deep_link'],
    requiredActions: ['BOOK_STAY22', 'OPEN_URL'],
    bridgeMode: 'fact_ack',
  }),
  luggage_practical: C({
    id: 'luggage_practical',
    agentIntent: 'booking',
    label: 'Gepäck / Schließfach',
    speechBudgetChars: 400,
    commitmentDefault: 'urgent',
    fastFacts: ['concrete_place', 'route_or_nav'],
    slowFacts: ['price_eur'],
    requiredActions: ['START_NAVIGATION', 'OPEN_URL'],
    bridgeMode: 'calm_help',
  }),
  emergency_care: C({
    id: 'emergency_care',
    agentIntent: 'emergency',
    label: 'Notfall / Gesundheit',
    speechBudgetChars: 480,
    commitmentDefault: 'urgent',
    fastFacts: ['emergency_right_facility', 'concrete_place', 'phone_or_nav'],
    slowFacts: ['open_now_or_hours'],
    requiredActions: ['START_NAVIGATION', 'DIAL_PHONE'],
    bridgeMode: 'urgency',
  }),
  safety_lost: C({
    id: 'safety_lost',
    agentIntent: 'emergency',
    label: 'Pass / Diebstahl / Sicherheit',
    speechBudgetChars: 500,
    commitmentDefault: 'urgent',
    fastFacts: ['concrete_place', 'phone_or_nav'],
    slowFacts: ['open_now_or_hours'],
    requiredActions: ['START_NAVIGATION', 'DIAL_PHONE'],
    bridgeMode: 'urgency',
  }),
  friction_now: C({
    id: 'friction_now',
    agentIntent: 'emergency',
    label: 'WC / ATM / Laden / Wasser',
    speechBudgetChars: 320,
    commitmentDefault: 'urgent',
    fastFacts: ['concrete_place', 'route_or_nav'],
    slowFacts: [],
    requiredActions: ['START_NAVIGATION'],
    bridgeMode: 'calm_help',
  }),
  sight_recommend: C({
    id: 'sight_recommend',
    agentIntent: 'knowledge',
    label: 'Sightseeing-Empfehlung',
    speechBudgetChars: 560,
    commitmentDefault: 'exploring',
    fastFacts: ['concrete_place', 'venue_options', 'route_or_nav'],
    slowFacts: ['ticket_or_info_url', 'price_eur'],
    requiredActions: ['START_NAVIGATION', 'OPEN_URL'],
    bridgeMode: 'motivate',
  }),
  poi_identify: C({
    id: 'poi_identify',
    agentIntent: 'knowledge',
    label: 'Was ist das Gebäude',
    speechBudgetChars: 520,
    commitmentDefault: 'exploring',
    fastFacts: ['concrete_place', 'number_answer'],
    slowFacts: [],
    requiredActions: ['SHOW_MORE'],
    bridgeMode: 'fact_ack',
  }),
  museum_theme: C({
    id: 'museum_theme',
    agentIntent: 'knowledge',
    label: 'Museum / Theme (Dino, Picasso…)',
    speechBudgetChars: 600,
    commitmentDefault: 'exploring',
    fastFacts: ['venue_options', 'hard_match_evidence'],
    slowFacts: ['price_eur', 'ticket_or_info_url'],
    requiredActions: ['OPEN_URL', 'START_NAVIGATION'],
    bridgeMode: 'motivate',
  }),
  tonight_live: C({
    id: 'tonight_live',
    agentIntent: 'knowledge',
    label: 'Kino / Theater / Konzert heute',
    speechBudgetChars: 560,
    commitmentDefault: 'exploring',
    fastFacts: ['showtimes_future', 'venue_options'],
    slowFacts: ['price_eur', 'ticket_or_info_url'],
    requiredActions: ['OPEN_URL'],
    bridgeMode: 'motivate',
  }),
  nightlife_vibe: C({
    id: 'nightlife_vibe',
    agentIntent: 'knowledge',
    label: 'Club / Bar / Party',
    speechBudgetChars: 540,
    commitmentDefault: 'exploring',
    fastFacts: ['venue_options', 'concrete_place'],
    slowFacts: ['price_eur', 'ticket_or_info_url', 'open_now_or_hours'],
    requiredActions: ['START_NAVIGATION', 'OPEN_URL'],
    bridgeMode: 'motivate',
  }),
  shopping_errand: C({
    id: 'shopping_errand',
    agentIntent: 'knowledge',
    label: 'Einkauf / Errand',
    speechBudgetChars: 420,
    commitmentDefault: 'committed',
    fastFacts: ['concrete_place', 'route_or_nav'],
    slowFacts: ['open_now_or_hours'],
    requiredActions: ['START_NAVIGATION'],
    bridgeMode: 'fact_ack',
  }),
  activity_sport: C({
    id: 'activity_sport',
    agentIntent: 'knowledge',
    label: 'Sport / Spikeball / Outdoor',
    speechBudgetChars: 560,
    commitmentDefault: 'exploring',
    fastFacts: ['concrete_place', 'activity_fit'],
    slowFacts: ['alternative_offered', 'price_eur'],
    requiredActions: ['START_NAVIGATION'],
    bridgeMode: 'motivate',
  }),
  weather_outfit: C({
    id: 'weather_outfit',
    agentIntent: 'umwelt',
    label: 'Wetter / Outfit',
    speechBudgetChars: 420,
    commitmentDefault: 'exploring',
    fastFacts: ['weather_or_outfit'],
    slowFacts: [],
    requiredActions: [],
    bridgeMode: 'motivate',
  }),
  day_plan_budget: C({
    id: 'day_plan_budget',
    agentIntent: 'knowledge',
    label: 'Tagesplan / Budget',
    speechBudgetChars: 620,
    commitmentDefault: 'exploring',
    fastFacts: ['venue_options', 'concrete_place'],
    slowFacts: ['price_eur', 'route_or_nav'],
    requiredActions: ['SHOW_MORE', 'START_NAVIGATION'],
    bridgeMode: 'motivate',
  }),
  fact_number: C({
    id: 'fact_number',
    agentIntent: 'knowledge',
    label: 'Fakten / Zahlen',
    speechBudgetChars: 380,
    commitmentDefault: 'exploring',
    fastFacts: ['number_answer'],
    slowFacts: [],
    requiredActions: [],
    bridgeMode: 'cheer',
  }),
  smalltalk_general: C({
    id: 'smalltalk_general',
    agentIntent: 'smalltalk',
    label: 'Smalltalk',
    speechBudgetChars: 280,
    commitmentDefault: 'exploring',
    fastFacts: [],
    slowFacts: [],
    requiredActions: [],
    bridgeMode: 'cheer',
  }),
};

export function getJobContract(id: FindusJobId): JobContract {
  return JOB_CONTRACTS[id];
}

export const ALL_JOB_IDS = Object.keys(JOB_CONTRACTS) as FindusJobId[];
