-- Findus Master-Schema für Supabase (public)
-- Primärquelle für die App: Storage-Bucket `staedte/<city_id>.json`
-- Tabellen pois/facts dienen als Dashboard-/Fallback-Spiegel.

create table if not exists public.pois (
  id bigint generated by default as identity primary key,
  name text not null,
  lat double precision not null,
  lng double precision not null,
  radius_meters double precision not null default 80
);

create table if not exists public.facts (
  id bigint generated by default as identity primary key,
  poi_id bigint not null references public.pois (id) on delete cascade,
  fact_text text not null
);

alter table public.pois enable row level security;
alter table public.facts enable row level security;

create policy "Public read pois"
  on public.pois for select
  using (true);

create policy "Public read facts"
  on public.facts for select
  using (true);

-- Shared weather cache: 1 fetch / city-Viertel (~5 km) or geo-cell (Edge Function only)
create table if not exists public.weather_cache (
  cache_key text primary key,
  lat double precision not null,
  lng double precision not null,
  city_hint text,
  open_meteo jsonb not null,
  owm jsonb,
  fetched_at timestamptz not null default now(),
  expires_at timestamptz not null
);

create index if not exists weather_cache_expires_at_idx
  on public.weather_cache (expires_at);

alter table public.weather_cache enable row level security;
-- No anon/authenticated policies: only service_role via weather-forecast Edge Function.

-- V7.0 Monthly City Clean-Up registry (server metadata check only — no client polling)
create table if not exists public.city_cleanup_registry (
  city_id text primary key,
  lat double precision not null,
  lng double precision not null,
  active boolean not null default true,
  last_sv_pano_id text,
  last_checked_at timestamptz,
  needs_rebuild boolean not null default false,
  rebuild_reason text,
  updated_at timestamptz not null default now()
);

alter table public.city_cleanup_registry enable row level security;
-- service_role only (Edge Function city-cleanup)

-- Community nav/Street View cache (client immediate + nightly push)
create table if not exists public.community_nav_cache (
  id bigint generated by default as identity primary key,
  city_hint text,
  landmarks_json jsonb,
  geocodes_json jsonb,
  street_views_json jsonb,
  source text,
  uploaded_at timestamptz not null default now()
);

alter table public.community_nav_cache enable row level security;

create policy "Anon insert community_nav_cache"
  on public.community_nav_cache for insert
  with check (true);

create policy "Public read community_nav_cache"
  on public.community_nav_cache for select
  using (true);

-- Community place tips (anonymisierte User-Meinungen zu Hotels/Restaurants)
create table if not exists public.community_place_feedback (
  id bigint generated by default as identity primary key,
  place_key text not null,
  place_name text not null,
  place_type text,
  lat double precision,
  lng double precision,
  city_hint text,
  sentiment smallint not null default 1,
  tip_text text,
  dish_mention text,
  created_at timestamptz not null default now()
);

create index if not exists community_place_feedback_place_key_idx
  on public.community_place_feedback (place_key);

create index if not exists community_place_feedback_geo_idx
  on public.community_place_feedback (lat, lng);

alter table public.community_place_feedback enable row level security;

create policy "Anon insert community_place_feedback"
  on public.community_place_feedback for insert
  with check (true);

create policy "Public read community_place_feedback"
  on public.community_place_feedback for select
  using (true);

-- Beta situation learning (crowd corrections → product blueprints)
create table if not exists public.beta_situation_events (
  id bigint generated by default as identity primary key,
  event_id text not null unique,
  contributor_hash text not null,
  situation_key text not null,
  intent_family text not null,
  tags text[] not null default '{}'::text[],
  expect text[] not null default '{}'::text[],
  avoid text[] not null default '{}'::text[],
  summary text,
  user_type_hint jsonb not null default '{}'::jsonb,
  correction_digest text,
  prior_user_digest text,
  created_at timestamptz not null default now()
);

create table if not exists public.situation_blueprint_candidates (
  situation_key text primary key,
  intent_family text not null,
  tags text[] not null default '{}'::text[],
  expect text[] not null default '{}'::text[],
  avoid text[] not null default '{}'::text[],
  summary text,
  unique_contributors int not null default 0,
  event_count int not null default 0,
  status text not null default 'pending'
    check (status in ('pending', 'auto_ready', 'promoted', 'rejected')),
  sample_digests text[] not null default '{}'::text[],
  updated_at timestamptz not null default now(),
  promoted_at timestamptz,
  promoted_by text
);

create table if not exists public.situation_blueprints_active (
  situation_key text primary key,
  intent_family text not null,
  tags text[] not null default '{}'::text[],
  expect text[] not null default '{}'::text[],
  avoid text[] not null default '{}'::text[],
  summary text not null,
  variants jsonb not null default '[]'::jsonb,
  source text not null default 'auto_3plus',
  version int not null default 1,
  updated_at timestamptz not null default now()
);

alter table public.beta_situation_events enable row level security;
alter table public.situation_blueprint_candidates enable row level security;
alter table public.situation_blueprints_active enable row level security;

-- Collective learning (crowd research + signals → all users)
create table if not exists public.community_discovered_places (
  place_key text primary key,
  city_hint text,
  name text not null,
  place_type text not null default 'place',
  lat double precision,
  lng double precision,
  fact_text text,
  source_url text,
  source_trust real not null default 0.4,
  contributor_hashes text[] not null default '{}'::text[],
  confirm_count int not null default 1,
  status text not null default 'pending'
    check (status in ('pending', 'active', 'rejected')),
  first_seen_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists community_discovered_places_city_idx
  on public.community_discovered_places (city_hint);
create index if not exists community_discovered_places_status_idx
  on public.community_discovered_places (status);

alter table public.community_discovered_places enable row level security;

create policy "Anon upsert community_discovered_places"
  on public.community_discovered_places for insert
  with check (true);

create policy "Anon update community_discovered_places"
  on public.community_discovered_places for update
  using (true);

create policy "Public read community_discovered_places"
  on public.community_discovered_places for select
  using (true);

create table if not exists public.community_learning_signals (
  id bigint generated by default as identity primary key,
  signal_id text not null unique,
  contributor_hash text not null,
  signal_kind text not null
    check (signal_kind in ('followup', 'error_avoid', 'cohort_style')),
  intent_family text not null default 'general',
  signal_key text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create unique index if not exists community_learning_signals_uniq_contrib
  on public.community_learning_signals (signal_key, contributor_hash);

alter table public.community_learning_signals enable row level security;

create policy "Anon insert community_learning_signals"
  on public.community_learning_signals for insert
  with check (true);

create policy "Public read community_learning_signals"
  on public.community_learning_signals for select
  using (true);

create table if not exists public.community_learning_promoted (
  signal_key text primary key,
  signal_kind text not null,
  intent_family text not null default 'general',
  payload jsonb not null default '{}'::jsonb,
  unique_contributors int not null default 0,
  source text not null default 'auto_3plus',
  version int not null default 1,
  updated_at timestamptz not null default now()
);

alter table public.community_learning_promoted enable row level security;

create policy "Public read community_learning_promoted"
  on public.community_learning_promoted for select
  using (true);

create policy "Anon upsert community_learning_promoted"
  on public.community_learning_promoted for insert
  with check (true);

create policy "Anon update community_learning_promoted"
  on public.community_learning_promoted for update
  using (true);
