-- Findus Master-Schema für Supabase (public)
-- Primärquelle für die App: Storage-Bucket `staedte/<city_id>.json`
-- Tabellen pois/facts dienen als Dashboard-/Fallback-Spiegel.

create table if not exists public.pois (
  id bigint generated by default as identity primary key,
  name text not null,
  lat double precision not null,
  lng double precision not null,
  radius_meters double precision not null default 80
);

create table if not exists public.facts (
  id bigint generated by default as identity primary key,
  poi_id bigint not null references public.pois (id) on delete cascade,
  fact_text text not null
);

alter table public.pois enable row level security;
alter table public.facts enable row level security;

create policy "Public read pois"
  on public.pois for select
  using (true);

create policy "Public read facts"
  on public.facts for select
  using (true);
