/**
 * Offline-Piktogramme für Bahnhof, Arzt, Parken, … — ohne HTTP-Sprites.
 */

export const HOME_MAP_AMENITY_IMAGES: Record<string, number> = {
  'place-rail': require('../../assets/homeMap/place-rail.png'),
  'place-bus': require('../../assets/homeMap/place-bus.png'),
  'place-doctor': require('../../assets/homeMap/place-doctor.png'),
  'place-pharmacy': require('../../assets/homeMap/place-pharmacy.png'),
  'place-parking': require('../../assets/homeMap/place-parking.png'),
  'place-restaurant': require('../../assets/homeMap/place-restaurant.png'),
  'place-cafe': require('../../assets/homeMap/place-cafe.png'),
  'place-bakery': require('../../assets/homeMap/place-bakery.png'),
  'place-shop': require('../../assets/homeMap/place-shop.png'),
  'place-souvenir': require('../../assets/homeMap/place-souvenir.png'),
  'place-toilet': require('../../assets/homeMap/place-toilet.png'),
  'place-post': require('../../assets/homeMap/place-post.png'),
  'place-fuel': require('../../assets/homeMap/place-fuel.png'),
  'place-supermarket': require('../../assets/homeMap/place-supermarket.png'),
  'place-kiosk': require('../../assets/homeMap/place-kiosk.png'),
  'place-bar': require('../../assets/homeMap/place-bar.png'),
  'place-info': require('../../assets/homeMap/place-info.png'),
  'place-viewpoint': require('../../assets/homeMap/place-viewpoint.png'),
  'place-park': require('../../assets/homeMap/place-park.png'),
  'place-nature': require('../../assets/homeMap/place-nature.png'),
  'place-historic': require('../../assets/homeMap/place-historic.png'),
  'place-activity': require('../../assets/homeMap/place-activity.png'),
  'place-camping': require('../../assets/homeMap/place-camping.png'),
  'place-hotel': require('../../assets/homeMap/place-hotel.png'),
  'place-hostel': require('../../assets/homeMap/place-hostel.png'),
  'place-attraction': require('../../assets/homeMap/place-attraction.png'),
  'place-museum': require('../../assets/homeMap/place-museum.png'),
  'place-cinema': require('../../assets/homeMap/place-cinema.png'),
  'place-theater': require('../../assets/homeMap/place-theater.png'),
  'place-water': require('../../assets/homeMap/place-water.png'),
  'place-bike': require('../../assets/homeMap/place-bike.png'),
  'place-atm': require('../../assets/homeMap/place-atm.png'),
  'place-ferry': require('../../assets/homeMap/place-ferry.png'),
  'user-arrow': require('../../assets/homeMap/user-arrow.png'),
  'route-chevron': require('../../assets/homeMap/route-chevron.png'),
  'route-label-pill': require('../../assets/homeMap/route-label-pill.png'),
  'route-pin-now': require('../../assets/homeMap/route-pin-now.png'),
  'route-pin-now-1': require('../../assets/homeMap/route-pin-now-1.png'),
  'route-pin-now-2': require('../../assets/homeMap/route-pin-now-2.png'),
  'route-pin-now-3': require('../../assets/homeMap/route-pin-now-3.png'),
  'route-pin-now-4': require('../../assets/homeMap/route-pin-now-4.png'),
  'route-pin-now-5': require('../../assets/homeMap/route-pin-now-5.png'),
  'route-pin-now-6': require('../../assets/homeMap/route-pin-now-6.png'),
  'route-pin-now-7': require('../../assets/homeMap/route-pin-now-7.png'),
  'route-pin-now-8': require('../../assets/homeMap/route-pin-now-8.png'),
  'route-pin-now-9': require('../../assets/homeMap/route-pin-now-9.png'),
  'route-pin-next-1': require('../../assets/homeMap/route-pin-next-1.png'),
  'route-pin-next-2': require('../../assets/homeMap/route-pin-next-2.png'),
  'route-pin-next-3': require('../../assets/homeMap/route-pin-next-3.png'),
  'route-pin-next-4': require('../../assets/homeMap/route-pin-next-4.png'),
  'route-pin-next-5': require('../../assets/homeMap/route-pin-next-5.png'),
  'route-pin-next-6': require('../../assets/homeMap/route-pin-next-6.png'),
  'route-pin-next-7': require('../../assets/homeMap/route-pin-next-7.png'),
  'route-pin-next-8': require('../../assets/homeMap/route-pin-next-8.png'),
  'route-pin-next-9': require('../../assets/homeMap/route-pin-next-9.png'),
};

const ICON_TO_IMAGE: Record<string, string> = {
  rail: 'place-rail',
  bus: 'place-bus',
  doctor: 'place-doctor',
  pharmacy: 'place-pharmacy',
  parking: 'place-parking',
  restaurant: 'place-restaurant',
  cafe: 'place-cafe',
  bakery: 'place-bakery',
  bar: 'place-bar',
  shop: 'place-shop',
  souvenir: 'place-souvenir',
  supermarket: 'place-supermarket',
  kiosk: 'place-kiosk',
  toilet: 'place-toilet',
  post: 'place-post',
  fuel: 'place-fuel',
  info: 'place-info',
  viewpoint: 'place-viewpoint',
  water: 'place-water',
  bike: 'place-bike',
  atm: 'place-atm',
  ferry: 'place-ferry',
  park: 'place-park',
  camping: 'place-camping',
  hotel: 'place-hotel',
  hostel: 'place-hostel',
  attraction: 'place-attraction',
  museum: 'place-museum',
  cinema: 'place-cinema',
  theater: 'place-theater',
  nature: 'place-nature',
  historic: 'place-historic',
  activity: 'place-activity',
};

export function amenityIconImageName(icon: string | undefined): string {
  if (!icon) return '';
  const mapped = ICON_TO_IMAGE[icon];
  if (mapped) return mapped;
  const fallback = `place-${icon}`;
  return HOME_MAP_AMENITY_IMAGES[fallback] != null ? fallback : '';
}
