/**
 * Schlanke Charakter-Optionen — nur IDs, die die Persona-Engine wirklich mappt.
 * EN-Labels bleiben für Legacy/Export; UI ist Deutsch.
 */

export type OptionItem = {
  id: string;
  emoji: string;
  labelDe: string;
  labelEn: string;
  infoDe: string;
  infoEn: string;
};

export type OptionCategory = {
  id: string;
  titleDe: string;
  titleEn: string;
  required: boolean;
  minSelect: number;
  maxSelect?: number;
  options: OptionItem[];
};

export const CHARACTER_CATEGORIES: OptionCategory[] = [
  {
    id: 'characters',
    titleDe: 'Findus Persönlichkeit',
    titleEn: 'Findus personality',
    required: true,
    minSelect: 1,
    maxSelect: 3,
    options: [
      {
        id: 'standard_char',
        emoji: '🙂',
        labelDe: 'Standard',
        labelEn: 'Standard',
        infoDe:
          'Freundlich, klar, alltagstauglich — passt für die meisten. Empfohlen zum Start.',
        infoEn: 'Friendly and clear — default for most travelers.',
      },
      {
        id: 'fuersorglich',
        emoji: '🤗',
        labelDe: 'Fürsorglich',
        labelEn: 'Caring',
        infoDe:
          'Familie, Pausen, Sicherheit — ideal für Eltern, Senioren, entspanntes Tempo.',
        infoEn: 'Breaks, safety, wellbeing — great for families.',
      },
      {
        id: 'coach',
        emoji: '💼',
        labelDe: 'Effizient',
        labelEn: 'Efficient',
        infoDe:
          'Kurz, klar, zielorientiert — Business, Layover, wenig Zeit.',
        infoEn: 'Short and goal-oriented — business & layovers.',
      },
      {
        id: 'historiker_char',
        emoji: '🏛️',
        labelDe: 'Geschichten',
        labelEn: 'Stories',
        infoDe: 'Kontext und Herkunft — warum steht das hier? Gut für Kulturfans.',
        infoEn: 'Context and origin stories.',
      },
      {
        id: 'genz_char',
        emoji: '🧢',
        labelDe: 'Locker & jung',
        labelEn: 'Casual & young',
        infoDe: 'Knapp, aktuelle Bezüge — Street-Smart statt Lehrbuch.',
        infoEn: 'Young and snappy with current references.',
      },
      {
        id: 'party',
        emoji: '🎉',
        labelDe: 'Nightlife',
        labelEn: 'Nightlife',
        infoDe: 'Bars, Clubs, Treffpunkte — für Partymacher und Abendpläne.',
        infoEn: 'High energy nightlife focus.',
      },
      {
        id: 'reiseblogger',
        emoji: '🌍',
        labelDe: 'Weltenbummler',
        labelEn: 'World traveler',
        infoDe: 'Foto-Winkel, Geheimtipps, Caps — für Entdecker und Backpacker.',
        infoEn: 'Photo angles and shareable tips.',
      },
      {
        id: 'lokalpatriot',
        emoji: '🏘️',
        labelDe: 'Insider',
        labelEn: 'Local insider',
        infoDe: 'Nachbarschaftsperspektive — weg von Touristenfallen.',
        infoEn: 'Local pride and insider angle.',
      },
      {
        id: 'poet',
        emoji: '✨',
        labelDe: 'Atmosphäre',
        labelEn: 'Atmosphere',
        infoDe: 'Stimmung und Bilder — eher Gefühl als Faktenliste.',
        infoEn: 'Imagery and atmosphere.',
      },
      {
        id: 'detektiv',
        emoji: '🕵️',
        labelDe: 'Neugierig',
        labelEn: 'Curious',
        infoDe: 'Spuren und kleine Rätsel — für Leute, die nachfragen mögen.',
        infoEn: 'Clues and mini mysteries.',
      },
      {
        id: 'mittelalter',
        emoji: '⚔️',
        labelDe: 'Sagen & Epochen',
        labelEn: 'Legends & eras',
        infoDe: 'Leichte historische Färbung — Burgen, Zünfte, Sagen (optional).',
        infoEn: 'Light medieval / legend tint.',
      },
    ],
  },
  {
    id: 'tonalities',
    titleDe: 'Tonalität',
    titleEn: 'Tone',
    required: true,
    minSelect: 1,
    maxSelect: 3,
    options: [
      {
        id: 'kumpelhaft',
        emoji: '🤝',
        labelDe: 'Kumpelhaft',
        labelEn: 'Buddy',
        infoDe: 'Du-Form, locker, wie mit einem Freund.',
        infoEn: 'Casual buddy tone.',
      },
      {
        id: 'umgangssprachlich',
        emoji: '💬',
        labelDe: 'Umgangssprachlich',
        labelEn: 'Colloquial',
        infoDe: 'Alltagssprache, kurze Sätze, wie gesprochen.',
        infoEn: 'Everyday spoken German.',
      },
      {
        id: 'erzaehlerisch',
        emoji: '📖',
        labelDe: 'Erzählerisch',
        labelEn: 'Narrative',
        infoDe: 'Mehr Story und Bilder — aber klar und konkret.',
        infoEn: 'More story, still concrete.',
      },
      {
        id: 'faktisch',
        emoji: '📌',
        labelDe: 'Faktisch',
        labelEn: 'Factual',
        infoDe: 'Dichte Infos, Zahlen, Kontext — wenig Schnickschnack.',
        infoEn: 'Dense facts, little fluff.',
      },
      {
        id: 'ernst',
        emoji: '🎩',
        labelDe: 'Ernst',
        labelEn: 'Serious',
        infoDe: 'Sachlich und respektvoll.',
        infoEn: 'Factual and respectful.',
      },
      {
        id: 'sarkastisch',
        emoji: '😏',
        labelDe: 'Sarkastisch',
        labelEn: 'Sarcastic',
        infoDe: 'Trockener Humor — nie verletzend.',
        infoEn: 'Dry humor, never mean.',
      },
      {
        id: 'maerchen',
        emoji: '🧚',
        labelDe: 'Märchen',
        labelEn: 'Fairy tale',
        infoDe: 'Zauberhafte Formulierungen.',
        infoEn: 'Enchanting phrasing.',
      },
      {
        id: 'krimi',
        emoji: '🔦',
        labelDe: 'Krimi',
        labelEn: 'Crime',
        infoDe: 'Spannung und Cliffhanger.',
        infoEn: 'Suspense and cliffhangers.',
      },
      {
        id: 'quiz',
        emoji: '❓',
        labelDe: 'Quiz',
        labelEn: 'Quiz',
        infoDe: 'Fragen stellen, dann auflösen.',
        infoEn: 'Ask then reveal.',
      },
      {
        id: 'doku',
        emoji: '🎬',
        labelDe: 'Doku',
        labelEn: 'Documentary',
        infoDe: 'Ruhige Erzählstimme wie in einer Doku.',
        infoEn: 'Calm documentary narration.',
      },
    ],
  },
  {
    id: 'motives',
    titleDe: 'Reisezweck',
    titleEn: 'Travel purpose',
    required: true,
    minSelect: 1,
    maxSelect: 3,
    options: [
      {
        id: 'urlaub',
        emoji: '🏖️',
        labelDe: 'Urlaub',
        labelEn: 'Holiday',
        infoDe: 'Entspannen und die Stadt genießen.',
        infoEn: 'Relax and enjoy the city.',
      },
      {
        id: 'kurztrip',
        emoji: '✈️',
        labelDe: 'Kurztrip',
        labelEn: 'Short trip',
        infoDe: 'Wenige Tage — Highlights kompakt.',
        infoEn: 'Few days — compact highlights.',
      },
      {
        id: 'wochenende',
        emoji: '🗓️',
        labelDe: 'Wochenendtrip',
        labelEn: 'Weekend trip',
        infoDe: 'Fr–So: gut getaktet, nicht hetzen.',
        infoEn: 'Fri–Sun: paced, not rushed.',
      },
      {
        id: 'partyurlaub',
        emoji: '🥳',
        labelDe: 'Partyurlaub',
        labelEn: 'Party trip',
        infoDe: 'Nightlife, Bars, Clubs im Fokus.',
        infoEn: 'Nightlife first.',
      },
      {
        id: 'freizeit',
        emoji: '☕',
        labelDe: 'Freizeit',
        labelEn: 'Leisure',
        infoDe: 'Klassischer Städtetrip — entdecken und genießen.',
        infoEn: 'Classic city trip.',
      },
      {
        id: 'business',
        emoji: '💼',
        labelDe: 'Business',
        labelEn: 'Business',
        infoDe: 'Effizient, zentrale Spots, wenig Fluff.',
        infoEn: 'Efficient, central, little fluff.',
      },
      {
        id: 'familie',
        emoji: '👨‍👩‍👧',
        labelDe: 'Familie',
        labelEn: 'Family',
        infoDe: 'Kinderfreundlich, kurze Etappen.',
        infoEn: 'Kid-friendly, short legs.',
      },
      {
        id: 'backpacker',
        emoji: '🎒',
        labelDe: 'Backpacker',
        labelEn: 'Backpacker',
        infoDe: 'Flexibel, günstig, Geheimtipps.',
        infoEn: 'Flexible, budget, hidden gems.',
      },
      {
        id: 'layover',
        emoji: '⏱️',
        labelDe: 'Zwischenstopp',
        labelEn: 'Layover',
        infoDe: 'Maximaler Eindruck in wenig Zeit.',
        infoEn: 'Maximum in little time.',
      },
    ],
  },
  {
    id: 'accessibility',
    titleDe: 'Barrierefreiheit & Bedürfnisse',
    titleEn: 'Accessibility & needs',
    required: false,
    minSelect: 0,
    options: [
      {
        id: 'rollstuhl',
        emoji: '♿',
        labelDe: 'Rollstuhl',
        labelEn: 'Wheelchair',
        infoDe: 'Stufenfreie Wege priorisieren.',
        infoEn: 'Step-free routes.',
      },
      {
        id: 'sehbehindert',
        emoji: '👁️',
        labelDe: 'Sehbehindert',
        labelEn: 'Low vision',
        infoDe: 'Mehr Audio-Detail, klare Wege.',
        infoEn: 'More audio detail.',
      },
      {
        id: 'hoerbehindert',
        emoji: '🦻',
        labelDe: 'Hörbehindert',
        labelEn: 'Hard of hearing',
        infoDe: 'Mehr Text/Untertitel, klarer sprechen.',
        infoEn: 'More text, clearer speech.',
      },
      {
        id: 'kinderwagen',
        emoji: '🍼',
        labelDe: 'Kinderwagen',
        labelEn: 'Stroller',
        infoDe: 'Rampen/Aufzüge, keine engen Treppen.',
        infoEn: 'Ramps and elevators.',
      },
      {
        id: 'gehbehindert',
        emoji: '🦵',
        labelDe: 'Gehbehindert',
        labelEn: 'Mobility limited',
        infoDe: 'Kürzere Distanzen, Sitzmöglichkeiten.',
        infoEn: 'Shorter distances, seating.',
      },
      {
        id: 'schwanger',
        emoji: '🤰',
        labelDe: 'Schwanger',
        labelEn: 'Pregnant',
        infoDe: 'Mehr Pausen, Toiletten, ruhige Strecken.',
        infoEn: 'More breaks and calmer stretches.',
      },
      {
        id: 'neuro',
        emoji: '🧠',
        labelDe: 'Neurodivergent',
        labelEn: 'Neurodivergent',
        infoDe: 'Weniger Reiz-Overload, klare Struktur.',
        infoEn: 'Less sensory overload.',
      },
      {
        id: 'lautstaerke',
        emoji: '🔇',
        labelDe: 'Lärmempfindlich',
        labelEn: 'Noise sensitive',
        infoDe: 'Laute Hotspots meiden, Vorwarnungen.',
        infoEn: 'Avoid loud hotspots.',
      },
      {
        id: 'hunde',
        emoji: '🐕',
        labelDe: 'Hund dabei',
        labelEn: 'With dog',
        infoDe: 'Hundefreundliche Orte priorisieren.',
        infoEn: 'Dog-friendly places.',
      },
      {
        id: 'kruecke',
        emoji: '🩹',
        labelDe: 'Mit Krücke / Gehhilfe',
        labelEn: 'With crutches',
        infoDe: 'Kürzere Wege, Aufzüge, Sitzplätze priorisieren.',
        infoEn: 'Shorter paths, elevators, seating.',
      },
    ],
  },
  {
    id: 'socialDynamics',
    titleDe: 'Mit wem reist du?',
    titleEn: 'Who are you traveling with?',
    required: true,
    minSelect: 1,
    maxSelect: 1,
    options: [
      {
        id: 'allein',
        emoji: '🧍',
        labelDe: 'Allein',
        labelEn: 'Solo',
        infoDe: 'Empfehlungen für Solo-Reisende — flexibel und spontan.',
        infoEn: 'Solo-friendly tips.',
      },
      {
        id: 'zu_zweit',
        emoji: '💑',
        labelDe: 'Zu zweit',
        labelEn: 'Couple',
        infoDe: 'Orte und Tempo für Paare.',
        infoEn: 'Couple pace and places.',
      },
      {
        id: 'date',
        emoji: '💘',
        labelDe: 'Date',
        labelEn: 'Date',
        infoDe: 'Romantische Spots, schöne Atmosphäre, Foto-tauglich.',
        infoEn: 'Romantic spots.',
      },
      {
        id: 'familie',
        emoji: '👨‍👩‍👧',
        labelDe: 'Familie',
        labelEn: 'Family',
        infoDe: 'Kinderfreundlich, kürzere Etappen, Pausen.',
        infoEn: 'Kid-friendly.',
      },
      {
        id: 'freundesgruppe',
        emoji: '👯',
        labelDe: 'Freundesgruppe',
        labelEn: 'Friends',
        infoDe: 'Gruppentauglich — Treffpunkte, Shared Experiences.',
        infoEn: 'Group-friendly.',
      },
    ],
  },
];

export type ExperienceCard = {
  id: string;
  category: 'wissen' | 'vibes' | 'mobilitaet' | 'tempo' | 'essen' | 'stil';
  emoji: string;
  labelDe: string;
  labelEn: string;
  noLabelDe: string;
  noLabelEn: string;
  yesLabelDe: string;
  yesLabelEn: string;
  /** Optional: Mitte statt „Neutral“ (z. B. Märkte: Gerne). */
  midLabelDe?: string;
  midLabelEn?: string;
};

export const EXPERIENCE_CARDS: ExperienceCard[] = [
  {
    id: 'museen',
    category: 'wissen',
    emoji: '🖼️',
    labelDe: 'Museen & Galerien',
    labelEn: 'Museums & galleries',
    noLabelDe: 'Eher nicht',
    noLabelEn: 'Rather not',
    yesLabelDe: 'Gerne',
    yesLabelEn: 'Yes please',
  },
  {
    id: 'denkmaeler',
    category: 'wissen',
    emoji: '🗿',
    labelDe: 'Denkmäler & Statuen',
    labelEn: 'Monuments & statues',
    noLabelDe: 'Eher nicht',
    noLabelEn: 'Rather not',
    yesLabelDe: 'Gerne',
    yesLabelEn: 'Yes please',
  },
  {
    id: 'theater_kultur',
    category: 'wissen',
    emoji: '🎭',
    labelDe: 'Theater & Konzerte',
    labelEn: 'Theater & concerts',
    noLabelDe: 'Eher nicht',
    noLabelEn: 'Rather not',
    yesLabelDe: 'Gerne',
    yesLabelEn: 'Yes please',
  },
  {
    id: 'kirchen',
    category: 'wissen',
    emoji: '⛪',
    labelDe: 'Kirchen & Sakrales',
    labelEn: 'Churches',
    noLabelDe: 'Eher nicht',
    noLabelEn: 'Rather not',
    yesLabelDe: 'Gerne',
    yesLabelEn: 'Yes please',
  },
  {
    id: 'architektur',
    category: 'wissen',
    emoji: '🏛️',
    labelDe: 'Architektur & Fassaden',
    labelEn: 'Architecture',
    noLabelDe: 'Eher nicht',
    noLabelEn: 'Rather not',
    yesLabelDe: 'Gerne',
    yesLabelEn: 'Yes please',
  },
  {
    id: 'streetart',
    category: 'wissen',
    emoji: '🎨',
    labelDe: 'Street Art & Murals',
    labelEn: 'Street art',
    noLabelDe: 'Eher nicht',
    noLabelEn: 'Rather not',
    yesLabelDe: 'Zeig mir',
    yesLabelEn: 'Show me',
  },
  {
    id: 'natur',
    category: 'vibes',
    emoji: '🌳',
    labelDe: 'Parks & Natur',
    labelEn: 'Parks & nature',
    noLabelDe: 'Stadt reicht',
    noLabelEn: 'City is fine',
    yesLabelDe: 'Gerne',
    yesLabelEn: 'Yes',
  },
  {
    id: 'wandern',
    category: 'vibes',
    emoji: '🥾',
    labelDe: 'Wanderwege & Lehrpfade',
    labelEn: 'Trails & walks',
    noLabelDe: 'Eher nicht',
    noLabelEn: 'Rather not',
    yesLabelDe: 'Gerne',
    yesLabelEn: 'Yes',
  },
  {
    id: 'freizeitparks',
    category: 'vibes',
    emoji: '🎢',
    labelDe: 'Freizeit, Zoo & Action',
    labelEn: 'Parks, zoo & action',
    noLabelDe: 'Eher nicht',
    noLabelEn: 'Rather not',
    yesLabelDe: 'Gerne',
    yesLabelEn: 'Yes',
  },
  {
    id: 'souvenirs',
    category: 'vibes',
    emoji: '🎁',
    labelDe: 'Souvenirs & Andenken',
    labelEn: 'Souvenirs',
    noLabelDe: 'Eher nicht',
    noLabelEn: 'Rather not',
    yesLabelDe: 'Tipp mich',
    yesLabelEn: 'Nudge me',
  },
  {
    id: 'sport',
    category: 'vibes',
    emoji: '⚽',
    labelDe: 'Sport & Stadion',
    labelEn: 'Sports',
    noLabelDe: 'Eher nicht',
    noLabelEn: 'Rather not',
    yesLabelDe: 'Interessiert',
    yesLabelEn: 'Interested',
  },
  {
    id: 'personen',
    category: 'wissen',
    emoji: '👤',
    labelDe: 'Berühmte Personen',
    labelEn: 'Famous people',
    noLabelDe: 'Weniger',
    noLabelEn: 'Less',
    yesLabelDe: 'Gerne',
    yesLabelEn: 'Yes',
  },
  {
    id: 'geheimtipps',
    category: 'vibes',
    emoji: '🗺️',
    labelDe: 'Geheimtipps',
    labelEn: 'Hidden gems',
    noLabelDe: 'Klassiker reicht',
    noLabelEn: 'Classics fine',
    yesLabelDe: 'Insider bitte',
    yesLabelEn: 'Insiders please',
  },
  {
    id: 'nachtleben',
    category: 'vibes',
    emoji: '🌙',
    labelDe: 'Nachtleben',
    labelEn: 'Nightlife',
    noLabelDe: 'Tagsüber',
    noLabelEn: 'Daytime',
    yesLabelDe: 'Abends aktiv',
    yesLabelEn: 'Evenings on',
  },
  {
    id: 'fuss',
    category: 'mobilitaet',
    emoji: '🚶',
    labelDe: 'Zu Fuß',
    labelEn: 'On foot',
    noLabelDe: 'Lieber nicht',
    noLabelEn: 'Rather not',
    yesLabelDe: 'Primär',
    yesLabelEn: 'Primary',
  },
  {
    id: 'oepnv',
    category: 'mobilitaet',
    emoji: '🚇',
    labelDe: 'ÖPNV',
    labelEn: 'Transit',
    noLabelDe: 'Selten',
    noLabelEn: 'Rarely',
    yesLabelDe: 'Gerne',
    yesLabelEn: 'Yes',
  },
  {
    id: 'fahrrad',
    category: 'mobilitaet',
    emoji: '🚲',
    labelDe: 'Fahrrad',
    labelEn: 'Bike',
    noLabelDe: 'Nein',
    noLabelEn: 'No',
    yesLabelDe: 'Ja',
    yesLabelEn: 'Yes',
  },
  {
    id: 'auto',
    category: 'mobilitaet',
    emoji: '🚗',
    labelDe: 'Auto',
    labelEn: 'Car',
    noLabelDe: 'Nein',
    noLabelEn: 'No',
    yesLabelDe: 'Ja',
    yesLabelEn: 'Yes',
  },
  {
    id: 'entspannt',
    category: 'tempo',
    emoji: '🐢',
    labelDe: 'Tour-Tempo',
    labelEn: 'Tour pace',
    noLabelDe: 'Schneller',
    noLabelEn: 'Faster',
    yesLabelDe: 'Langsam',
    yesLabelEn: 'Slow',
  },
  {
    id: 'vegetarisch',
    category: 'essen',
    emoji: '🥗',
    labelDe: 'Vegetarisch',
    labelEn: 'Vegetarian',
    noLabelDe: 'Egal',
    noLabelEn: 'Either',
    yesLabelDe: 'Ja',
    yesLabelEn: 'Yes',
  },
  {
    id: 'vegan',
    category: 'essen',
    emoji: '🌱',
    labelDe: 'Vegan',
    labelEn: 'Vegan',
    noLabelDe: 'Egal',
    noLabelEn: 'Either',
    yesLabelDe: 'Ja',
    yesLabelEn: 'Yes',
  },
  {
    id: 'budget',
    category: 'essen',
    emoji: '💶',
    labelDe: 'Großzügiges Budget (ca. 150 €/Tag)',
    labelEn: 'Generous budget',
    noLabelDe: 'Sparsam (~40 €)',
    noLabelEn: 'Budget',
    yesLabelDe: 'Komfort (~150 €)',
    yesLabelEn: 'Comfort',
  },
  {
    id: 'typisch_touri',
    category: 'stil',
    emoji: '🗺️',
    labelDe: 'Typisch Touri',
    labelEn: 'Classic tourist',
    noLabelDe: 'Eher nicht',
    noLabelEn: 'Rather not',
    yesLabelDe: 'Gerne',
    yesLabelEn: 'Yes please',
  },
  {
    id: 'weg_vom_trubel',
    category: 'stil',
    emoji: '🌿',
    labelDe: 'Keine Massen',
    labelEn: 'No crowds',
    noLabelDe: 'Eher nicht',
    noLabelEn: 'Rather not',
    yesLabelDe: 'Gerne',
    yesLabelEn: 'Yes please',
  },
  {
    id: 'familie_tauglich',
    category: 'vibes',
    emoji: '👨‍👩‍👧',
    labelDe: 'Familienfreundlich',
    labelEn: 'Family-friendly',
    noLabelDe: 'Eher nicht',
    noLabelEn: 'Rather not',
    yesLabelDe: 'Gerne',
    yesLabelEn: 'Yes please',
  },
  {
    id: 'business_spots',
    category: 'stil',
    emoji: '💼',
    labelDe: 'Business',
    labelEn: 'Business',
    noLabelDe: 'Eher nicht',
    noLabelEn: 'Rather not',
    yesLabelDe: 'Gerne',
    yesLabelEn: 'Yes please',
  },
  {
    id: 'shopping',
    category: 'vibes',
    emoji: '🛍️',
    labelDe: 'Shopping & Boutiquen',
    labelEn: 'Shopping',
    noLabelDe: 'Eher nicht',
    noLabelEn: 'Rather not',
    yesLabelDe: 'Gerne',
    yesLabelEn: 'Yes',
  },
  {
    id: 'kulinarik',
    category: 'essen',
    emoji: '🍽️',
    labelDe: 'Kulinarik & Restaurants',
    labelEn: 'Food & restaurants',
    noLabelDe: 'Einfach essen',
    noLabelEn: 'Simple food',
    yesLabelDe: 'Highlights',
    yesLabelEn: 'Highlights',
  },
  {
    id: 'aussichten',
    category: 'vibes',
    emoji: '🌅',
    labelDe: 'Aussichten & Skyline',
    labelEn: 'Views & skyline',
    noLabelDe: 'Weniger',
    noLabelEn: 'Less',
    yesLabelDe: 'Gerne',
    yesLabelEn: 'Yes',
  },
  {
    id: 'lokale_maerkte',
    category: 'vibes',
    emoji: '🧺',
    labelDe: 'Märkte & Straßenleben',
    labelEn: 'Markets & street life',
    noLabelDe: 'Satt',
    noLabelEn: 'Enough',
    yesLabelDe: 'Zeig mir',
    yesLabelEn: 'Show me',
    midLabelDe: 'Gerne',
    midLabelEn: 'Gladly',
  },
  {
    id: 'barriere_care',
    category: 'mobilitaet',
    emoji: '♿',
    labelDe: 'Besondere Bedürfnisse',
    labelEn: 'Accessibility needs',
    noLabelDe: 'Nein',
    noLabelEn: 'No',
    yesLabelDe: 'Ja',
    yesLabelEn: 'Yes',
  },
  {
    id: 'tour_stops',
    category: 'tempo',
    emoji: '📍',
    labelDe: 'Tourlänge (Stops)',
    labelEn: 'Tour length (stops)',
    noLabelDe: 'Weniger Stops',
    noLabelEn: 'Fewer stops',
    yesLabelDe: 'Mehr Stops',
    yesLabelEn: 'More stops',
  },
  {
    id: 'kurztrip',
    category: 'tempo',
    emoji: '⏱️',
    labelDe: 'Kurze Touren (Legacy)',
    labelEn: 'Short tours (legacy)',
    noLabelDe: 'Lange Touren',
    noLabelEn: 'Long tours',
    yesLabelDe: 'Kurze Touren',
    yesLabelEn: 'Short tours',
  },
];

export const EXPERIENCE_CATEGORY_TITLES: Record<
  ExperienceCard['category'],
  { de: string; en: string }
> = {
  wissen: {
    de: 'Jetzt aber — was spricht dich an',
    en: 'Now — what resonates with you',
  },
  vibes: {
    de: 'Jetzt aber — was spricht dich an',
    en: 'Now — what resonates with you',
  },
  mobilitaet: { de: 'Mobilität', en: 'Mobility' },
  tempo: { de: 'Tourlänge', en: 'Tour length' },
  essen: { de: 'Essen & Budget', en: 'Food & budget' },
  stil: { de: 'Reise-Stil', en: 'Travel style' },
};

/** Reise-Stil ohne Insta — Keine Massen + Business (+ optional Touri). */
export const TRAVEL_STYLE_CARD_IDS = [
  'weg_vom_trubel',
  'business_spots',
  'typisch_touri',
] as const;

/** Kompakte Interessen für Express-Einrichtung — diverse User-Typen. */
export const EXPRESS_INTEREST_IDS = [
  'museen',
  'denkmaeler',
  'theater_kultur',
  'aussichten',
  'natur',
  'wandern',
  'freizeitparks',
  'souvenirs',
  'kulinarik',
  'lokale_maerkte',
  'nachtleben',
  'familie_tauglich',
  'weg_vom_trubel',
  'personen',
] as const;
