/**
 * Schlanke Charakter-Optionen — nur IDs, die die Persona-Engine wirklich mappt.
 * EN-Labels bleiben für Legacy/Export; UI ist Deutsch.
 */

export type OptionItem = {
  id: string;
  emoji: string;
  labelDe: string;
  labelEn: string;
  infoDe: string;
  infoEn: string;
};

export type OptionCategory = {
  id: string;
  titleDe: string;
  titleEn: string;
  required: boolean;
  minSelect: number;
  maxSelect?: number;
  options: OptionItem[];
};

export const CHARACTER_CATEGORIES: OptionCategory[] = [
  {
    id: 'characters',
    titleDe: 'Findus Persönlichkeit',
    titleEn: 'Findus personality',
    required: true,
    minSelect: 1,
    maxSelect: 1,
    options: [
      {
        id: 'genz_char',
        emoji: '🧢',
        labelDe: 'Gen Z',
        labelEn: 'Gen Z',
        infoDe:
          'Jung, knapp, aktuelle Bezüge — weniger Lehrbuch, mehr Street-Smart.',
        infoEn: 'Young and snappy with current references.',
      },
      {
        id: 'historiker_char',
        emoji: '🏛️',
        labelDe: 'Historiker',
        labelEn: 'Historian',
        infoDe: 'Kontext, Herkunft und Zusammenhänge — warum steht das hier?',
        infoEn: 'Context and origin stories.',
      },
      {
        id: 'mittelalter',
        emoji: '⚔️',
        labelDe: 'Mittelalter',
        labelEn: 'Medieval',
        infoDe: 'Leicht mittelalterliche Färbung — Burgen, Zünfte, Sagen.',
        infoEn: 'Light medieval tint.',
      },
      {
        id: 'party',
        emoji: '🎉',
        labelDe: 'Party',
        labelEn: 'Party',
        infoDe: 'Energie hoch — Nightlife, Treffpunkte, was gerade abgeht.',
        infoEn: 'High energy nightlife focus.',
      },
      {
        id: 'coach',
        emoji: '💪',
        labelDe: 'Coach',
        labelEn: 'Coach',
        infoDe: 'Motivierend, klar, mit kleinen Challenges.',
        infoEn: 'Motivating with small challenges.',
      },
      {
        id: 'fuersorglich',
        emoji: '🤗',
        labelDe: 'Fürsorglich',
        labelEn: 'Caring',
        infoDe: 'Pausen, Sicherheit, Wohlbefinden — wie ein guter Freund.',
        infoEn: 'Breaks, safety, wellbeing.',
      },
      {
        id: 'poet',
        emoji: '✨',
        labelDe: 'Poet',
        labelEn: 'Poet',
        infoDe: 'Bildhafte Sprache, Stimmung, Atmosphäre.',
        infoEn: 'Imagery and atmosphere.',
      },
      {
        id: 'lokalpatriot',
        emoji: '🏘️',
        labelDe: 'Lokalpatriot',
        labelEn: 'Local pride',
        infoDe: 'Insider-Perspektive und Nachbarschaftsstolz.',
        infoEn: 'Local pride and insider angle.',
      },
      {
        id: 'detektiv',
        emoji: '🕵️',
        labelDe: 'Detektiv',
        labelEn: 'Detective',
        infoDe: 'Spuren, Rätsel, neugierige Fragen zu Orten.',
        infoEn: 'Clues and mini mysteries.',
      },
      {
        id: 'reiseblogger',
        emoji: '📱',
        labelDe: 'Reiseblogger',
        labelEn: 'Travel blogger',
        infoDe: 'Foto-Winkel, Caps, „das musst du posten“.',
        infoEn: 'Photo angles and shareable tips.',
      },
    ],
  },
  {
    id: 'tonalities',
    titleDe: 'Tonalität',
    titleEn: 'Tone',
    required: true,
    minSelect: 1,
    maxSelect: 1,
    options: [
      {
        id: 'kumpelhaft',
        emoji: '🤝',
        labelDe: 'Kumpelhaft',
        labelEn: 'Buddy',
        infoDe: 'Du-Form, locker, wie mit einem Freund.',
        infoEn: 'Casual buddy tone.',
      },
      {
        id: 'ernst',
        emoji: '🎩',
        labelDe: 'Ernst',
        labelEn: 'Serious',
        infoDe: 'Sachlich und respektvoll.',
        infoEn: 'Factual and respectful.',
      },
      {
        id: 'sarkastisch',
        emoji: '😏',
        labelDe: 'Sarkastisch',
        labelEn: 'Sarcastic',
        infoDe: 'Trockener Humor — nie verletzend.',
        infoEn: 'Dry humor, never mean.',
      },
      {
        id: 'maerchen',
        emoji: '🧚',
        labelDe: 'Märchen',
        labelEn: 'Fairy tale',
        infoDe: 'Zauberhafte Formulierungen.',
        infoEn: 'Enchanting phrasing.',
      },
      {
        id: 'krimi',
        emoji: '🔦',
        labelDe: 'Krimi',
        labelEn: 'Crime',
        infoDe: 'Spannung und Cliffhanger.',
        infoEn: 'Suspense and cliffhangers.',
      },
      {
        id: 'quiz',
        emoji: '❓',
        labelDe: 'Quiz',
        labelEn: 'Quiz',
        infoDe: 'Fragen stellen, dann auflösen.',
        infoEn: 'Ask then reveal.',
      },
      {
        id: 'doku',
        emoji: '🎬',
        labelDe: 'Doku',
        labelEn: 'Documentary',
        infoDe: 'Ruhige Erzählstimme wie in einer Doku.',
        infoEn: 'Calm documentary narration.',
      },
    ],
  },
  {
    id: 'motives',
    titleDe: 'Reisezweck',
    titleEn: 'Travel purpose',
    required: true,
    minSelect: 1,
    maxSelect: 1,
    options: [
      {
        id: 'freizeit',
        emoji: '☕',
        labelDe: 'Freizeit',
        labelEn: 'Leisure',
        infoDe: 'Klassischer Städtetrip — entdecken und genießen.',
        infoEn: 'Classic city trip.',
      },
      {
        id: 'business',
        emoji: '💼',
        labelDe: 'Business',
        labelEn: 'Business',
        infoDe: 'Effizient, zentrale Spots, wenig Fluff.',
        infoEn: 'Efficient, central, little fluff.',
      },
      {
        id: 'familie',
        emoji: '👨‍👩‍👧',
        labelDe: 'Familie',
        labelEn: 'Family',
        infoDe: 'Kinderfreundlich, kurze Etappen.',
        infoEn: 'Kid-friendly, short legs.',
      },
      {
        id: 'backpacker',
        emoji: '🎒',
        labelDe: 'Backpacker',
        labelEn: 'Backpacker',
        infoDe: 'Flexibel, günstig, Geheimtipps.',
        infoEn: 'Flexible, budget, hidden gems.',
      },
      {
        id: 'layover',
        emoji: '⏱️',
        labelDe: 'Zwischenstopp',
        labelEn: 'Layover',
        infoDe: 'Maximaler Eindruck in wenig Zeit.',
        infoEn: 'Maximum in little time.',
      },
    ],
  },
  {
    id: 'accessibility',
    titleDe: 'Barrierefreiheit & Bedürfnisse',
    titleEn: 'Accessibility & needs',
    required: false,
    minSelect: 0,
    options: [
      {
        id: 'rollstuhl',
        emoji: '♿',
        labelDe: 'Rollstuhl',
        labelEn: 'Wheelchair',
        infoDe: 'Stufenfreie Wege priorisieren.',
        infoEn: 'Step-free routes.',
      },
      {
        id: 'sehbehindert',
        emoji: '👁️',
        labelDe: 'Sehbehindert',
        labelEn: 'Low vision',
        infoDe: 'Mehr Audio-Detail, klare Wege.',
        infoEn: 'More audio detail.',
      },
      {
        id: 'hoerbehindert',
        emoji: '🦻',
        labelDe: 'Hörbehindert',
        labelEn: 'Hard of hearing',
        infoDe: 'Mehr Text/Untertitel, klarer sprechen.',
        infoEn: 'More text, clearer speech.',
      },
      {
        id: 'kinderwagen',
        emoji: '🍼',
        labelDe: 'Kinderwagen',
        labelEn: 'Stroller',
        infoDe: 'Rampen/Aufzüge, keine engen Treppen.',
        infoEn: 'Ramps and elevators.',
      },
      {
        id: 'gehbehindert',
        emoji: '🦵',
        labelDe: 'Gehbehindert',
        labelEn: 'Mobility limited',
        infoDe: 'Kürzere Distanzen, Sitzmöglichkeiten.',
        infoEn: 'Shorter distances, seating.',
      },
      {
        id: 'schwanger',
        emoji: '🤰',
        labelDe: 'Schwanger',
        labelEn: 'Pregnant',
        infoDe: 'Mehr Pausen, Toiletten, ruhige Strecken.',
        infoEn: 'More breaks and calmer stretches.',
      },
      {
        id: 'neuro',
        emoji: '🧠',
        labelDe: 'Neurodivergent',
        labelEn: 'Neurodivergent',
        infoDe: 'Weniger Reiz-Overload, klare Struktur.',
        infoEn: 'Less sensory overload.',
      },
      {
        id: 'lautstaerke',
        emoji: '🔇',
        labelDe: 'Lärmempfindlich',
        labelEn: 'Noise sensitive',
        infoDe: 'Laute Hotspots meiden, Vorwarnungen.',
        infoEn: 'Avoid loud hotspots.',
      },
      {
        id: 'hunde',
        emoji: '🐕',
        labelDe: 'Hund dabei',
        labelEn: 'With dog',
        infoDe: 'Hundefreundliche Orte priorisieren.',
        infoEn: 'Dog-friendly places.',
      },
      {
        id: 'kruecke',
        emoji: '🩹',
        labelDe: 'Mit Krücke / Gehhilfe',
        labelEn: 'With crutches',
        infoDe: 'Kürzere Wege, Aufzüge, Sitzplätze priorisieren.',
        infoEn: 'Shorter paths, elevators, seating.',
      },
    ],
  },
  {
    id: 'socialDynamics',
    titleDe: 'Mit wem reist du?',
    titleEn: 'Who are you traveling with?',
    required: true,
    minSelect: 1,
    maxSelect: 1,
    options: [
      {
        id: 'allein',
        emoji: '🧍',
        labelDe: 'Allein',
        labelEn: 'Solo',
        infoDe: 'Empfehlungen für Solo-Reisende — flexibel und spontan.',
        infoEn: 'Solo-friendly tips.',
      },
      {
        id: 'zu_zweit',
        emoji: '💑',
        labelDe: 'Zu zweit',
        labelEn: 'Couple',
        infoDe: 'Orte und Tempo für Paare.',
        infoEn: 'Couple pace and places.',
      },
      {
        id: 'date',
        emoji: '💘',
        labelDe: 'Date',
        labelEn: 'Date',
        infoDe: 'Romantische Spots, schöne Atmosphäre, Foto-tauglich.',
        infoEn: 'Romantic spots.',
      },
      {
        id: 'familie',
        emoji: '👨‍👩‍👧',
        labelDe: 'Familie',
        labelEn: 'Family',
        infoDe: 'Kinderfreundlich, kürzere Etappen, Pausen.',
        infoEn: 'Kid-friendly.',
      },
      {
        id: 'freundesgruppe',
        emoji: '👯',
        labelDe: 'Freundesgruppe',
        labelEn: 'Friends',
        infoDe: 'Gruppentauglich — Treffpunkte, Shared Experiences.',
        infoEn: 'Group-friendly.',
      },
    ],
  },
];

export type ExperienceCard = {
  id: string;
  category: 'wissen' | 'vibes' | 'mobilitaet' | 'tempo' | 'essen' | 'stil';
  emoji: string;
  labelDe: string;
  labelEn: string;
  noLabelDe: string;
  noLabelEn: string;
  yesLabelDe: string;
  yesLabelEn: string;
};

export const EXPERIENCE_CARDS: ExperienceCard[] = [
  {
    id: 'jahreszahlen',
    category: 'wissen',
    emoji: '📅',
    labelDe: 'Viele Jahreszahlen & Fakten',
    labelEn: 'Lots of dates & facts',
    noLabelDe: 'Lieber wenig',
    noLabelEn: 'Prefer less',
    yesLabelDe: 'Gerne viel',
    yesLabelEn: 'Prefer lots',
  },
  {
    id: 'geschichte',
    category: 'wissen',
    emoji: '📜',
    labelDe: 'Geschichten & Kontext',
    labelEn: 'Stories & context',
    noLabelDe: 'Knapp halten',
    noLabelEn: 'Keep short',
    yesLabelDe: 'Ausführlich',
    yesLabelEn: 'Go deep',
  },
  {
    id: 'museen',
    category: 'wissen',
    emoji: '🖼️',
    labelDe: 'Museen',
    labelEn: 'Museums',
    noLabelDe: 'Eher nicht',
    noLabelEn: 'Rather not',
    yesLabelDe: 'Gerne',
    yesLabelEn: 'Yes please',
  },
  {
    id: 'kirchen',
    category: 'wissen',
    emoji: '⛪',
    labelDe: 'Kirchen & Sakrales',
    labelEn: 'Churches',
    noLabelDe: 'Überspringen',
    noLabelEn: 'Skip',
    yesLabelDe: 'Interessiert',
    yesLabelEn: 'Interested',
  },
  {
    id: 'personen',
    category: 'wissen',
    emoji: '👤',
    labelDe: 'Berühmte Personen',
    labelEn: 'Famous people',
    noLabelDe: 'Weniger',
    noLabelEn: 'Less',
    yesLabelDe: 'Gerne',
    yesLabelEn: 'Yes',
  },
  {
    id: 'geheimtipps',
    category: 'vibes',
    emoji: '🗺️',
    labelDe: 'Geheimtipps',
    labelEn: 'Hidden gems',
    noLabelDe: 'Klassiker reicht',
    noLabelEn: 'Classics fine',
    yesLabelDe: 'Insider bitte',
    yesLabelEn: 'Insiders please',
  },
  {
    id: 'nachtleben',
    category: 'vibes',
    emoji: '🌙',
    labelDe: 'Nachtleben',
    labelEn: 'Nightlife',
    noLabelDe: 'Tagsüber',
    noLabelEn: 'Daytime',
    yesLabelDe: 'Abends aktiv',
    yesLabelEn: 'Evenings on',
  },
  {
    id: 'fuss',
    category: 'mobilitaet',
    emoji: '🚶',
    labelDe: 'Zu Fuß',
    labelEn: 'On foot',
    noLabelDe: 'Lieber nicht',
    noLabelEn: 'Rather not',
    yesLabelDe: 'Primär',
    yesLabelEn: 'Primary',
  },
  {
    id: 'oepnv',
    category: 'mobilitaet',
    emoji: '🚇',
    labelDe: 'ÖPNV',
    labelEn: 'Transit',
    noLabelDe: 'Selten',
    noLabelEn: 'Rarely',
    yesLabelDe: 'Gerne',
    yesLabelEn: 'Yes',
  },
  {
    id: 'fahrrad',
    category: 'mobilitaet',
    emoji: '🚲',
    labelDe: 'Fahrrad',
    labelEn: 'Bike',
    noLabelDe: 'Nein',
    noLabelEn: 'No',
    yesLabelDe: 'Ja',
    yesLabelEn: 'Yes',
  },
  {
    id: 'auto',
    category: 'mobilitaet',
    emoji: '🚗',
    labelDe: 'Auto',
    labelEn: 'Car',
    noLabelDe: 'Nein',
    noLabelEn: 'No',
    yesLabelDe: 'Ja',
    yesLabelEn: 'Yes',
  },
  {
    id: 'entspannt',
    category: 'tempo',
    emoji: '🐢',
    labelDe: 'Entspanntes Tempo',
    labelEn: 'Relaxed pace',
    noLabelDe: 'Schneller',
    noLabelEn: 'Faster',
    yesLabelDe: 'Langsam',
    yesLabelEn: 'Slow',
  },
  {
    id: 'vegetarisch',
    category: 'essen',
    emoji: '🥗',
    labelDe: 'Vegetarisch',
    labelEn: 'Vegetarian',
    noLabelDe: 'Egal',
    noLabelEn: 'Either',
    yesLabelDe: 'Ja',
    yesLabelEn: 'Yes',
  },
  {
    id: 'vegan',
    category: 'essen',
    emoji: '🌱',
    labelDe: 'Vegan',
    labelEn: 'Vegan',
    noLabelDe: 'Egal',
    noLabelEn: 'Either',
    yesLabelDe: 'Ja',
    yesLabelEn: 'Yes',
  },
  {
    id: 'budget',
    category: 'essen',
    emoji: '💶',
    labelDe: 'Großzügiges Budget (ca. 150 €/Tag)',
    labelEn: 'Generous budget',
    noLabelDe: 'Sparsam (~40 €)',
    noLabelEn: 'Budget',
    yesLabelDe: 'Komfort (~150 €)',
    yesLabelEn: 'Comfort',
  },
  {
    id: 'insta',
    category: 'stil',
    emoji: '📸',
    labelDe: 'Insta-Fotos dürfen sein',
    labelEn: 'Instagram-worthy',
    noLabelDe: 'Egal',
    noLabelEn: 'Whatever',
    yesLabelDe: 'Gerne Spots',
    yesLabelEn: 'Show me spots',
  },
  {
    id: 'typisch_touri',
    category: 'stil',
    emoji: '🗺️',
    labelDe: 'Typisch Touri',
    labelEn: 'Classic tourist',
    noLabelDe: 'Lieber nicht',
    noLabelEn: 'Rather not',
    yesLabelDe: 'Must-sees bitte',
    yesLabelEn: 'Must-sees please',
  },
  {
    id: 'weg_vom_trubel',
    category: 'stil',
    emoji: '🌿',
    labelDe: 'Weg vom Trubel',
    labelEn: 'Away from crowds',
    noLabelDe: 'Trubel ok',
    noLabelEn: 'Crowds ok',
    yesLabelDe: 'Ruhige Orte',
    yesLabelEn: 'Quiet places',
  },
];

export const EXPERIENCE_CATEGORY_TITLES: Record<
  ExperienceCard['category'],
  { de: string; en: string }
> = {
  wissen: { de: 'Wissen & Kultur', en: 'Knowledge & culture' },
  vibes: { de: 'Vibes', en: 'Vibes' },
  mobilitaet: { de: 'Mobilität', en: 'Mobility' },
  tempo: { de: 'Tempo', en: 'Pace' },
  essen: { de: 'Essen & Budget', en: 'Food & budget' },
  stil: { de: 'Reise-Stil', en: 'Travel style' },
};

/** Kompakte Interessen für Express-Einrichtung. */
export const EXPRESS_INTEREST_IDS = [
  'jahreszahlen',
  'geheimtipps',
  'nachtleben',
  'museen',
  'vegetarisch',
  'insta',
  'typisch_touri',
  'weg_vom_trubel',
] as const;
