export type OptionItem = {
  id: string;
  emoji: string;
  /** Kurzlabel DE */
  labelDe: string;
  labelEn: string;
  /** Erklärung für das Info-„i“ */
  infoDe: string;
  infoEn: string;
};

export type OptionCategory = {
  id: string;
  titleDe: string;
  titleEn: string;
  required: boolean;
  minSelect: number;
  /** Wenn gesetzt: höchstens so viele Optionen (z. B. 1 = Einzelnauswahl). */
  maxSelect?: number;
  options: OptionItem[];
};

export const CHARACTER_CATEGORIES: OptionCategory[] = [
  {
    id: 'characters',
    titleDe: 'Findus Persönlichkeit',
    titleEn: 'Findus personality',
    required: true,
    minSelect: 1,
    maxSelect: 1,
    options: [
      {
        id: 'genz_char',
        emoji: '🧢',
        labelDe: 'Gen Z',
        labelEn: 'Gen Z',
        infoDe:
          'Findus spricht jung, knapp und mit aktuellen Bezügen — weniger Lehrbuch, mehr Street-Smart.',
        infoEn:
          'Findus sounds young and snappy with current references — less textbook, more street-smart.',
      },
      {
        id: 'historiker_char',
        emoji: '🏛️',
        labelDe: 'Historiker',
        labelEn: 'Historian',
        infoDe:
          'Mehr Kontext, Herkunft und „warum steht das hier?“ — Findus denkt in Epochen und Zusammenhängen.',
        infoEn:
          'More context and origin stories — Findus thinks in eras and connections.',
      },
      {
        id: 'mittelalter',
        emoji: '⚔️',
        labelDe: 'Mittelalter',
        labelEn: 'Medieval',
        infoDe:
          'Burgen, Zünfte, Sagen: Findus färbt Erklärungen leicht mittelalterlich ein, ohne unverständlich zu werden.',
        infoEn:
          'Castles, guilds, legends: a light medieval tint without becoming unreadable.',
      },
      {
        id: 'party',
        emoji: '🎉',
        labelDe: 'Party',
        labelEn: 'Party',
        infoDe:
          'Energie hoch, Fokus auf Nightlife, Treffpunkte und was gerade abgeht.',
        infoEn:
          'High energy — nightlife, hangouts, and what is happening right now.',
      },
      {
        id: 'coach',
        emoji: '💪',
        labelDe: 'Coach',
        labelEn: 'Coach',
        infoDe:
          'Motivierend, klar, mit kleinen Challenges: „Schaffst du den Aussichtspunkt?“',
        infoEn:
          'Motivating and clear, with small challenges: “Can you make the viewpoint?”',
      },
      {
        id: 'fuersorglich',
        emoji: '🤗',
        labelDe: 'Fürsorglich',
        labelEn: 'Caring',
        infoDe:
          'Achtet auf Pausen, Sicherheit und Wohlbefinden — wie ein guter Freund an der Seite.',
        infoEn:
          'Watches for breaks, safety, and wellbeing — like a good friend beside you.',
      },
      {
        id: 'poet',
        emoji: '✨',
        labelDe: 'Poet',
        labelEn: 'Poet',
        infoDe:
          'Bildhafte Sprache, Stimmung und Atmosphäre — Orte werden zu kleinen Geschichten.',
        infoEn:
          'Imagery and atmosphere — places become little stories.',
      },
      {
        id: 'lokalpatriot',
        emoji: '🏘️',
        labelDe: 'Lokalpatriot',
        labelEn: 'Local pride',
        infoDe:
          'Stolz auf die Gegend, Insider-Witze und echte Nachbarschafts-Perspektive.',
        infoEn:
          'Local pride, insider jokes, and a true neighborhood perspective.',
      },
      {
        id: 'detektiv',
        emoji: '🕵️',
        labelDe: 'Detektiv',
        labelEn: 'Detective',
        infoDe:
          'Findus stellt Fragen, findet Spuren und macht aus Orten kleine Rätsel.',
        infoEn:
          'Findus asks questions, finds clues, and turns places into mini mysteries.',
      },
      {
        id: 'reiseblogger',
        emoji: '📱',
        labelDe: 'Reiseblogger',
        labelEn: 'Travel blogger',
        infoDe:
          'Tipps wie für Social Media: Foto-Winkel, Caps, „das musst du posten“.',
        infoEn:
          'Tips like for social: photo angles, captions, “you have to post this”.',
      },
    ],
  },
  {
    id: 'tonalities',
    titleDe: 'Tonalität & Stil',
    titleEn: 'Tone & style',
    required: true,
    minSelect: 1,
    options: [
      {
        id: 'ernst',
        emoji: '🎩',
        labelDe: 'Ernst',
        labelEn: 'Serious',
        infoDe: 'Sachlich und respektvoll — ideal für Gedenkorte und Fakten.',
        infoEn: 'Factual and respectful — ideal for memorials and facts.',
      },
      {
        id: 'kumpelhaft',
        emoji: '🤝',
        labelDe: 'Kumpelhaft',
        labelEn: 'Buddy',
        infoDe: 'Du-Form, locker, wie mit einem Freund unterwegs.',
        infoEn: 'Casual you-form — like walking with a buddy.',
      },
      {
        id: 'humorvoll',
        emoji: '😄',
        labelDe: 'Humorvoll',
        labelEn: 'Funny',
        infoDe: 'Witzige Einschübe, ohne die Info zu opfern.',
        infoEn: 'Witty asides without dropping the useful info.',
      },
      {
        id: 'sarkastisch',
        emoji: '😏',
        labelDe: 'Sarkastisch',
        labelEn: 'Sarcastic',
        infoDe: 'Trockener Humor und leichte Spitzen — nie verletzend.',
        infoEn: 'Dry humor and light digs — never mean.',
      },
      {
        id: 'herold',
        emoji: '📯',
        labelDe: 'Herold',
        labelEn: 'Herald',
        infoDe: 'Feierlich ankündigen: „Vernehmet!“ — große Momente.',
        infoEn: 'Ceremonial announcements for big moments.',
      },
      {
        id: 'maerchen',
        emoji: '🧚',
        labelDe: 'Märchen',
        labelEn: 'Fairy tale',
        infoDe: 'Zauberhafte Formulierungen, sanfte Spannung.',
        infoEn: 'Enchanting phrasing and gentle suspense.',
      },
      {
        id: 'einfach',
        emoji: '🧩',
        labelDe: 'Einfach',
        labelEn: 'Simple',
        infoDe: 'Kurze Sätze, klare Worte — gut für Kinder oder Fokus.',
        infoEn: 'Short sentences, plain words — great for kids or focus.',
      },
      {
        id: 'krimi',
        emoji: '🔦',
        labelDe: 'Krimi',
        labelEn: 'Crime',
        infoDe: 'Spannungsbögen, Cliffhanger, „wer war’s?“-Feeling.',
        infoEn: 'Suspense arcs and cliffhangers — whodunit vibes.',
      },
      {
        id: 'quiz',
        emoji: '❓',
        labelDe: 'Quiz',
        labelEn: 'Quiz',
        infoDe: 'Findus stellt Fragen und lässt dich raten, bevor er auflöst.',
        infoEn: 'Findus asks you to guess before revealing answers.',
      },
      {
        id: 'blogger',
        emoji: '✍️',
        labelDe: 'Blogger',
        labelEn: 'Blogger',
        infoDe: 'Persönliche Empfehlungen im „Ich war hier“-Ton.',
        infoEn: 'Personal recs in an “I was here” tone.',
      },
      {
        id: 'podcast',
        emoji: '🎧',
        labelDe: 'Podcast',
        labelEn: 'Podcast',
        infoDe: 'Gesprächig, mit kleinen Cliffhangern zwischen Fakten.',
        infoEn: 'Conversational, with mini cliffhangers between facts.',
      },
      {
        id: 'dokufilm',
        emoji: '🎬',
        labelDe: 'Dokufilm',
        labelEn: 'Documentary',
        infoDe: 'Ruhige Erzählstimme wie in einer guten Doku.',
        infoEn: 'Calm narration like a good documentary.',
      },
    ],
  },
  {
    id: 'motives',
    titleDe: 'Reisemotiv & Aktivität',
    titleEn: 'Travel motive & activity',
    required: true,
    minSelect: 1,
    options: [
      {
        id: 'business',
        emoji: '💼',
        labelDe: 'Business',
        labelEn: 'Business',
        infoDe: 'Effizient, relevante Orte, wenig Fluff — Zeit ist knapp.',
        infoEn: 'Efficient, relevant spots, little fluff — time is tight.',
      },
      {
        id: 'party_motive',
        emoji: '🪩',
        labelDe: 'Party',
        labelEn: 'Party',
        infoDe: 'Bars, Events, Nightlife zuerst.',
        infoEn: 'Bars, events, nightlife first.',
      },
      {
        id: 'kultur',
        emoji: '🎭',
        labelDe: 'Kultur',
        labelEn: 'Culture',
        infoDe: 'Museen, Kunst, Architektur und Geschichten.',
        infoEn: 'Museums, art, architecture, and stories.',
      },
      {
        id: 'foodie',
        emoji: '🍜',
        labelDe: 'Foodie',
        labelEn: 'Foodie',
        infoDe: 'Cafés, Restaurants, Spezialitäten und Snack-Stops.',
        infoEn: 'Cafés, restaurants, specialties, and snack stops.',
      },
      {
        id: 'shopping',
        emoji: '🛍️',
        labelDe: 'Shopping',
        labelEn: 'Shopping',
        infoDe: 'Läden, Märkte, Design und lokale Produkte.',
        infoEn: 'Shops, markets, design, and local products.',
      },
      {
        id: 'natur',
        emoji: '🌲',
        labelDe: 'Natur',
        labelEn: 'Nature',
        infoDe: 'Parks, Wege, Wasser und ruhige Grünflächen.',
        infoEn: 'Parks, paths, water, and quiet green spaces.',
      },
      {
        id: 'urban',
        emoji: '🏙️',
        labelDe: 'Urban',
        labelEn: 'Urban',
        infoDe: 'Street Art, Viertel-Vibes, Stadtgefühl.',
        infoEn: 'Street art, neighborhood vibes, city pulse.',
      },
      {
        id: 'entspannt',
        emoji: '☕',
        labelDe: 'Entspannt',
        labelEn: 'Relaxed',
        infoDe: 'Langsame Route, Sitzgelegenheiten, wenig Stress.',
        infoEn: 'Slow route, places to sit, low stress.',
      },
      {
        id: 'express',
        emoji: '🚀',
        labelDe: 'Express',
        labelEn: 'Express',
        infoDe: 'Highlights in Kurzform — maximaler Output, minimale Zeit.',
        infoEn: 'Highlights only — max output, min time.',
      },
      {
        id: 'sportlich',
        emoji: '🏃',
        labelDe: 'Sportlich',
        labelEn: 'Sporty',
        infoDe: 'Längere Wege, Bewegung, Aktiv-Spots.',
        infoEn: 'Longer walks, movement, active spots.',
      },
      {
        id: 'familie',
        emoji: '👨‍👩‍👧',
        labelDe: 'Familie',
        labelEn: 'Family',
        infoDe: 'Kinderfreundlich, Spielplätze, kurze Etappen.',
        infoEn: 'Kid-friendly, playgrounds, short legs.',
      },
      {
        id: 'romantik',
        emoji: '💞',
        labelDe: 'Romantik',
        labelEn: 'Romance',
        infoDe: 'Schöne Spots zu zweit, Sonnenuntergänge, ruhige Ecken.',
        infoEn: 'Couple spots, sunsets, quiet corners.',
      },
      {
        id: 'fotografie',
        emoji: '📷',
        labelDe: 'Fotografie',
        labelEn: 'Photography',
        infoDe: 'Beste Lichtzeiten und Motiv-Ideen.',
        infoEn: 'Best light and shot ideas.',
      },
    ],
  },
  {
    id: 'accessibility',
    titleDe: 'Barrierefreiheit & Bedürfnisse',
    titleEn: 'Accessibility & needs',
    required: false,
    minSelect: 0,
    options: [
      {
        id: 'rollstuhl',
        emoji: '♿',
        labelDe: 'Rollstuhl',
        labelEn: 'Wheelchair',
        infoDe: 'Bevorzugt stufenfreie Wege und zugängliche Orte.',
        infoEn: 'Prefers step-free routes and accessible places.',
      },
      {
        id: 'sehbehindert',
        emoji: '👁️',
        labelDe: 'Sehbehindert',
        labelEn: 'Low vision',
        infoDe: 'Mehr Audio-Detail, klare Wegbeschreibungen, weniger „schau mal“.',
        infoEn: 'More audio detail, clear directions, less “look there”.',
      },
      {
        id: 'kinderwagen',
        emoji: '🍼',
        labelDe: 'Kinderwagen',
        labelEn: 'Stroller',
        infoDe: 'Vermeidet Treppen und enge Pfade, sucht Aufzüge/Rampen.',
        infoEn: 'Avoids stairs and tight paths; looks for elevators/ramps.',
      },
      {
        id: 'gehbehindert',
        emoji: '🦵',
        labelDe: 'Gehbehindert',
        labelEn: 'Mobility limited',
        infoDe: 'Kürzere Distanzen, Sitzmöglichkeiten, flache Wege.',
        infoEn: 'Shorter distances, seating, flatter paths.',
      },
      {
        id: 'neuro',
        emoji: '🧠',
        labelDe: 'Neurodivergent',
        labelEn: 'Neurodivergent',
        infoDe: 'Weniger Reiz-Overload, klare Struktur, vorhersagbare Ansagen.',
        infoEn: 'Less sensory overload, clear structure, predictable cues.',
      },
      {
        id: 'konjunktiv',
        emoji: '🗣️',
        labelDe: 'Einfache Sprache',
        labelEn: 'Plain language',
        infoDe: 'Vermeidet komplexe Schachtelsätze und Fachjargon.',
        infoEn: 'Avoids complex sentences and jargon.',
      },
      {
        id: 'schwanger',
        emoji: '🤰',
        labelDe: 'Schwanger',
        labelEn: 'Pregnant',
        infoDe: 'Mehr Pausen, Schatten, Toiletten und ruhige Strecken.',
        infoEn: 'More breaks, shade, restrooms, calmer stretches.',
      },
      {
        id: 'hunde',
        emoji: '🐕',
        labelDe: 'Hund dabei',
        labelEn: 'With dog',
        infoDe: 'Hunde-freundliche Orte und Grünflächen priorisieren.',
        infoEn: 'Prioritize dog-friendly places and green areas.',
      },
      {
        id: 'platzangst',
        emoji: '🚪',
        labelDe: 'Platzangst',
        labelEn: 'Claustrophobia',
        infoDe: 'Vermeidet enge Unterführungen und volle Innenräume.',
        infoEn: 'Avoids tight underpasses and crowded indoors.',
      },
      {
        id: 'allergiker',
        emoji: '🤧',
        labelDe: 'Allergiker',
        labelEn: 'Allergies',
        infoDe: 'Hinweise zu Pollen, Tieren oder typischen Reizstoffen, wenn bekannt.',
        infoEn: 'Notes on pollen, animals, or common irritants when known.',
      },
      {
        id: 'hoerbehindert',
        emoji: '🦻',
        labelDe: 'Hörbehindert',
        labelEn: 'Hard of hearing',
        infoDe: 'Mehr Text/Untertitel, langsameres Sprechen möglich.',
        infoEn: 'More text/subtitles; slower speech available.',
      },
      {
        id: 'lautstaerke',
        emoji: '🔇',
        labelDe: 'Lärmempfindlich',
        labelEn: 'Noise sensitive',
        infoDe: 'Meidet laute Hotspots und gibt Vorwarnungen.',
        infoEn: 'Avoids loud hotspots and gives advance warnings.',
      },
    ],
  },
  {
    id: 'socialDynamics',
    titleDe: 'Sozialdynamik',
    titleEn: 'Social dynamics',
    required: true,
    minSelect: 1,
    options: [
      {
        id: 'intro',
        emoji: '🤫',
        labelDe: 'Intro',
        labelEn: 'Introvert',
        infoDe:
          'Ruhigere Orte, weniger Crowds, Findus hält sich zurück und gibt dir Raum.',
        infoEn:
          'Quieter places, fewer crowds — Findus stays low-key and gives you space.',
      },
      {
        id: 'extro',
        emoji: '🗣️',
        labelDe: 'Extro',
        labelEn: 'Extrovert',
        infoDe: 'Mehr Interaktion, lebendige Spots, Gesprächsanlässe.',
        infoEn: 'More interaction, lively spots, conversation starters.',
      },
      {
        id: 'wingman',
        emoji: '😎',
        labelDe: 'Wingman',
        labelEn: 'Wingman',
        infoDe:
          'Findus kuppelt dich mit Insider-Spots und Tipps, wo man leicht Anschluss findet — Bars, Events, offene Treffpunkte.',
        infoEn:
          'Findus steers you to insider spots where meeting people is easy — bars, events, open hangouts.',
      },
      {
        id: 'team',
        emoji: '👥',
        labelDe: 'Team',
        labelEn: 'Team',
        infoDe: 'Inhalte für Gruppen: Abstimmungen, gemeinsame Entscheidungen.',
        infoEn: 'Content for groups: votes and shared decisions.',
      },
      {
        id: 'frieden',
        emoji: '☮️',
        labelDe: 'Frieden',
        labelEn: 'Peace',
        infoDe: 'Konfliktarme Themen, harmonische Stimmung, kein Stress.',
        infoEn: 'Low-conflict topics, harmonious mood, no stress.',
      },
      {
        id: 'foto',
        emoji: '🤳',
        labelDe: 'Foto',
        labelEn: 'Photo',
        infoDe: 'Findus erinnert dich an gute Motive und Posen-Momente.',
        infoEn: 'Findus nudges you toward great shots and pose moments.',
      },
      {
        id: 'variation',
        emoji: '🎲',
        labelDe: 'Variation',
        labelEn: 'Variety',
        infoDe: 'Abwechslung: mal Geschichte, mal Food, mal Aussicht.',
        infoEn: 'Variety: history, food, views — mixed on purpose.',
      },
      {
        id: 'diskussion',
        emoji: '💬',
        labelDe: 'Diskussion',
        labelEn: 'Discussion',
        infoDe: 'Findus wirft Thesen ein und lädt zum Nachdenken ein.',
        infoEn: 'Findus drops theses and invites reflection.',
      },
      {
        id: 'sharing',
        emoji: '🔗',
        labelDe: 'Sharing',
        labelEn: 'Sharing',
        infoDe: 'Tipps so formuliert, dass du sie leicht weitergeben kannst.',
        infoEn: 'Tips phrased so you can easily share them.',
      },
      {
        id: 'lokalheld',
        emoji: '🦸',
        labelDe: 'Lokalheld',
        labelEn: 'Local hero',
        infoDe: 'Du lernst Orte wie ein Einheimischer — mit Verantwortung und Stolz.',
        infoEn: 'You learn places like a local — with pride and care.',
      },
      {
        id: 'allein',
        emoji: '🧍',
        labelDe: 'Alleinreisend',
        labelEn: 'Solo travel',
        infoDe: 'Sicherheitstipps und Orte, die sich solo gut anfühlen.',
        infoEn: 'Safety tips and places that feel good solo.',
      },
      {
        id: 'date',
        emoji: '💘',
        labelDe: 'Date',
        labelEn: 'Date',
        infoDe: 'Gesprächsstarter und romantische Mini-Momente für zwei.',
        infoEn: 'Conversation starters and romantic mini-moments for two.',
      },
    ],
  },
  {
    id: 'travelParty',
    titleDe: 'Reisekontext',
    titleEn: 'Travel context',
    required: false,
    minSelect: 0,
    maxSelect: 1,
    options: [
      {
        id: 'backpacker',
        emoji: '🎒',
        labelDe: 'Backpacker',
        labelEn: 'Backpacker',
        infoDe: 'Günstig, flexibel, Hostels und Geheimtipps.',
        infoEn: 'Budget-friendly, flexible, hostels and hidden gems.',
      },
      {
        id: 'geschaeftsreise',
        emoji: '✈️',
        labelDe: 'Geschäftsreise',
        labelEn: 'Business trip',
        infoDe: 'Kurze Fenster, zentrale Spots, wenig Umwege.',
        infoEn: 'Short windows, central spots, few detours.',
      },
      {
        id: 'freundesgruppe',
        emoji: '🍻',
        labelDe: 'Freundesgruppe',
        labelEn: 'Friends group',
        infoDe: 'Aktivitäten, die für mehrere Spaß machen.',
        infoEn: 'Activities that work for a group.',
      },
      {
        id: 'zwischenstopp',
        emoji: '⏱️',
        labelDe: 'Zwischenstopp',
        labelEn: 'Layover',
        infoDe: 'Maximaler Eindruck in wenig Zeit.',
        infoEn: 'Maximum impression in little time.',
      },
      {
        id: 'weltenbummler',
        emoji: '🌍',
        labelDe: 'Weltenbummler',
        labelEn: 'World traveler',
        infoDe: 'Vergleiche zu anderen Städten und „typisch hier“-Momente.',
        infoEn: 'Comparisons to other cities and “typical here” moments.',
      },
    ],
  },
];

export type ExperienceCard = {
  id: string;
  category: 'wissen' | 'vibes' | 'mobilitaet' | 'tempo' | 'essen';
  emoji: string;
  labelDe: string;
  labelEn: string;
  noLabelDe: string;
  noLabelEn: string;
  yesLabelDe: string;
  yesLabelEn: string;
};

export const EXPERIENCE_CARDS: ExperienceCard[] = [
  // Wissen & Kultur
  {
    id: 'jahreszahlen',
    category: 'wissen',
    emoji: '📅',
    labelDe: 'Viele Jahreszahlen & Fakten',
    labelEn: 'Lots of dates & facts',
    noLabelDe: 'Lieber wenig',
    noLabelEn: 'Prefer less',
    yesLabelDe: 'Immer her damit',
    yesLabelEn: 'Bring them on',
  },
  {
    id: 'geschichte',
    category: 'wissen',
    emoji: '🏺',
    labelDe: 'Viel Geschichte',
    labelEn: 'Lots of history',
    noLabelDe: 'Nicht so mein Ding',
    noLabelEn: 'Not my thing',
    yesLabelDe: 'Erzähl mir alles',
    yesLabelEn: 'Tell me everything',
  },
  {
    id: 'museen',
    category: 'wissen',
    emoji: '🖼️',
    labelDe: 'Museen & Ausstellungen',
    labelEn: 'Museums & exhibitions',
    noLabelDe: 'Überspringen',
    noLabelEn: 'Skip',
    yesLabelDe: 'Unbedingt',
    yesLabelEn: 'Absolutely',
  },
  {
    id: 'kirchen',
    category: 'wissen',
    emoji: '⛪',
    labelDe: 'Kirchen & Sakrales',
    labelEn: 'Churches & sacred sites',
    noLabelDe: 'Eher nicht',
    noLabelEn: 'Rather not',
    yesLabelDe: 'Interessant',
    yesLabelEn: 'Interesting',
  },
  {
    id: 'architektur',
    category: 'wissen',
    emoji: '🏛️',
    labelDe: 'Fassaden & Architektur',
    labelEn: 'Facades & architecture',
    noLabelDe: 'Egal',
    noLabelEn: 'Whatever',
    yesLabelDe: 'Liebe ich',
    yesLabelEn: 'Love it',
  },
  {
    id: 'legenden',
    category: 'wissen',
    emoji: '👻',
    labelDe: 'Sagen & Legenden',
    labelEn: 'Myths & legends',
    noLabelDe: 'Nein danke',
    noLabelEn: 'No thanks',
    yesLabelDe: 'Gerne gruselig',
    yesLabelEn: 'Spooky please',
  },
  {
    id: 'personen',
    category: 'wissen',
    emoji: '👤',
    labelDe: 'Berühmte Personen',
    labelEn: 'Famous people',
    noLabelDe: 'Weniger',
    noLabelEn: 'Less',
    yesLabelDe: 'Namen bitte',
    yesLabelEn: 'Names please',
  },
  {
    id: 'kino_im_kopf',
    category: 'wissen',
    emoji: '🎬',
    labelDe: 'Kino im Kopf (bildliche Vergleiche)',
    labelEn: 'Cinema in the mind (vivid comparisons)',
    noLabelDe: 'Sachlicher',
    noLabelEn: 'More literal',
    yesLabelDe: 'Alles bildlich',
    yesLabelEn: 'Make it visual',
  },
  {
    id: 'anekdoten',
    category: 'wissen',
    emoji: '🎭',
    labelDe: 'Anekdoten & Dramen',
    labelEn: 'Anecdotes & drama',
    noLabelDe: 'Lieber Fakten',
    noLabelEn: 'Prefer facts',
    yesLabelDe: 'Geschichten bitte',
    yesLabelEn: 'Stories please',
  },
  {
    id: 'fun_facts',
    category: 'wissen',
    emoji: '✨',
    labelDe: 'Fun Facts & Kurioses',
    labelEn: 'Fun facts & curiosities',
    noLabelDe: 'Ohne',
    noLabelEn: 'Skip',
    yesLabelDe: 'Immer rein',
    yesLabelEn: 'Always include',
  },
  // Vibes
  {
    id: 'events',
    category: 'vibes',
    emoji: '🎟️',
    labelDe: 'Aktuelle Events',
    labelEn: 'Current events',
    noLabelDe: 'Nicht nötig',
    noLabelEn: 'Not needed',
    yesLabelDe: 'Was geht heute?',
    yesLabelEn: "What's on today?",
  },
  {
    id: 'nachtleben',
    category: 'vibes',
    emoji: '🌙',
    labelDe: 'Nachtleben & Partys',
    labelEn: 'Nightlife & parties',
    noLabelDe: 'Ruhig bleiben',
    noLabelEn: 'Keep it chill',
    yesLabelDe: 'Party an',
    yesLabelEn: 'Party on',
  },
  {
    id: 'touri',
    category: 'vibes',
    emoji: '📸',
    labelDe: 'Touri-Must-Haves',
    labelEn: 'Tourist must-sees',
    noLabelDe: 'Zu touristisch',
    noLabelEn: 'Too touristy',
    yesLabelDe: 'Klassiker bitte',
    yesLabelEn: 'Classics please',
  },
  {
    id: 'geheimtipps',
    category: 'vibes',
    emoji: '🤫',
    labelDe: 'Geheimtipps',
    labelEn: 'Hidden gems',
    noLabelDe: 'Standard reicht',
    noLabelEn: 'Standard is fine',
    yesLabelDe: 'Insider only',
    yesLabelEn: 'Insider only',
  },
  {
    id: 'instagram',
    category: 'vibes',
    emoji: '✨',
    labelDe: 'Instagram-Spots',
    labelEn: 'Instagram spots',
    noLabelDe: 'Kein Content-Zwang',
    noLabelEn: 'No content pressure',
    yesLabelDe: 'Foto-ready',
    yesLabelEn: 'Photo-ready',
  },
  {
    id: 'einheimisch',
    category: 'vibes',
    emoji: '🏠',
    labelDe: 'Echt einheimisch',
    labelEn: 'Truly local',
    noLabelDe: 'Egal',
    noLabelEn: 'Whatever',
    yesLabelDe: 'Wie ein Local',
    yesLabelEn: 'Like a local',
  },
  {
    id: 'panorama',
    category: 'vibes',
    emoji: '🔭',
    labelDe: 'Aussichten & Panoramen',
    labelEn: 'Views & panoramas',
    noLabelDe: 'Kein Klettern',
    noLabelEn: 'No climbing',
    yesLabelDe: 'Höher bitte',
    yesLabelEn: 'Higher please',
  },
  {
    id: 'streetart',
    category: 'vibes',
    emoji: '🎨',
    labelDe: 'Street Art & Szene',
    labelEn: 'Street art & scene',
    noLabelDe: 'Nicht mein Vibes',
    noLabelEn: 'Not my vibe',
    yesLabelDe: 'Szene zeigen',
    yesLabelEn: 'Show the scene',
  },
  // Mobilität
  {
    id: 'fuss',
    category: 'mobilitaet',
    emoji: '🚶',
    labelDe: 'Gut zu Fuß',
    labelEn: 'Good on foot',
    noLabelDe: 'Lieber wenig laufen',
    noLabelEn: 'Prefer less walking',
    yesLabelDe: 'Laufen ist okay',
    yesLabelEn: 'Walking is fine',
  },
  {
    id: 'eingeschraenkt',
    category: 'mobilitaet',
    emoji: '♿',
    labelDe: 'Eingeschränkt mobil',
    labelEn: 'Limited mobility',
    noLabelDe: 'Trifft nicht zu',
    noLabelEn: 'Does not apply',
    yesLabelDe: 'Bitte berücksichtigen',
    yesLabelEn: 'Please consider',
  },
  {
    id: 'fahrrad',
    category: 'mobilitaet',
    emoji: '🚲',
    labelDe: 'Fahrrad',
    labelEn: 'Bike',
    noLabelDe: 'Ohne Rad',
    noLabelEn: 'No bike',
    yesLabelDe: 'Rad dabei / ok',
    yesLabelEn: 'Bike ok',
  },
  {
    id: 'eroller',
    category: 'mobilitaet',
    emoji: '🛴',
    labelDe: 'E-Roller',
    labelEn: 'E-scooter',
    noLabelDe: 'Nein',
    noLabelEn: 'No',
    yesLabelDe: 'Ja, gerne',
    yesLabelEn: 'Yes please',
  },
  {
    id: 'oepnv',
    category: 'mobilitaet',
    emoji: '🚌',
    labelDe: 'Bus & Bahn',
    labelEn: 'Bus & train',
    noLabelDe: 'Lieber nicht',
    noLabelEn: 'Rather not',
    yesLabelDe: 'ÖPNV ok',
    yesLabelEn: 'Transit ok',
  },
  {
    id: 'faehre',
    category: 'mobilitaet',
    emoji: '⛴️',
    labelDe: 'Fähre',
    labelEn: 'Ferry',
    noLabelDe: 'Nein',
    noLabelEn: 'No',
    yesLabelDe: 'Wenn möglich',
    yesLabelEn: 'If possible',
  },
  {
    id: 'auto',
    category: 'mobilitaet',
    emoji: '🚗',
    labelDe: 'Auto',
    labelEn: 'Car',
    noLabelDe: 'Ohne Auto',
    noLabelEn: 'No car',
    yesLabelDe: 'Auto verfügbar',
    yesLabelEn: 'Car available',
  },
  {
    id: 'rollstuhl_mob',
    category: 'mobilitaet',
    emoji: '♿',
    labelDe: 'Rollstuhl-Routen',
    labelEn: 'Wheelchair routes',
    noLabelDe: 'Nicht nötig',
    noLabelEn: 'Not needed',
    yesLabelDe: 'Wichtig',
    yesLabelEn: 'Important',
  },
  {
    id: 'kruecken',
    category: 'mobilitaet',
    emoji: '🩺',
    labelDe: 'Krücken / Gehhilfe',
    labelEn: 'Crutches / aid',
    noLabelDe: 'Nein',
    noLabelEn: 'No',
    yesLabelDe: 'Ja, bitte sanft',
    yesLabelEn: 'Yes, keep it gentle',
  },
  // Tempo
  {
    id: 'zeit_lassen',
    category: 'tempo',
    emoji: '🐢',
    labelDe: 'Zeit lassen',
    labelEn: 'Take it slow',
    noLabelDe: 'Zügig bitte',
    noLabelEn: 'Keep moving',
    yesLabelDe: 'Ganz gemütlich',
    yesLabelEn: 'Nice and easy',
  },
  {
    id: 'viele_pausen',
    category: 'tempo',
    emoji: '🪑',
    labelDe: 'Viele Pausen',
    labelEn: 'Many breaks',
    noLabelDe: 'Wenige Pausen',
    noLabelEn: 'Few breaks',
    yesLabelDe: 'Oft rasten',
    yesLabelEn: 'Rest often',
  },
  {
    id: 'antwortlaenge',
    category: 'tempo',
    emoji: '📝',
    labelDe: 'Antwortlänge der KI',
    labelEn: 'AI answer length',
    noLabelDe: 'Kurz',
    noLabelEn: 'Short',
    yesLabelDe: 'Ausführlich',
    yesLabelEn: 'Detailed',
  },
  {
    id: 'tourlaenge',
    category: 'tempo',
    emoji: '🗺️',
    labelDe: 'Tourlänge',
    labelEn: 'Tour length',
    noLabelDe: 'Kurz',
    noLabelEn: 'Short',
    yesLabelDe: 'Lang',
    yesLabelEn: 'Long',
  },
  // Essen & Budget
  {
    id: 'budget',
    category: 'essen',
    emoji: '💶',
    labelDe: 'Budget pro Tag',
    labelEn: 'Daily budget',
    noLabelDe: 'Sparsam (<30€)',
    noLabelEn: 'Budget (<€30)',
    yesLabelDe: 'Luxus (>150€)',
    yesLabelEn: 'Luxury (>€150)',
  },
  {
    id: 'fruehstueck',
    category: 'essen',
    emoji: '🥐',
    labelDe: 'Frühstücken gehen',
    labelEn: 'Go for breakfast',
    noLabelDe: 'Nein',
    noLabelEn: 'No',
    yesLabelDe: 'Ja bitte',
    yesLabelEn: 'Yes please',
  },
  {
    id: 'kaffee',
    category: 'essen',
    emoji: '☕',
    labelDe: 'Kaffee trinken',
    labelEn: 'Coffee stops',
    noLabelDe: 'Nein',
    noLabelEn: 'No',
    yesLabelDe: 'Immer',
    yesLabelEn: 'Always',
  },
  {
    id: 'abendessen',
    category: 'essen',
    emoji: '🍽️',
    labelDe: 'Abendessen',
    labelEn: 'Dinner',
    noLabelDe: 'Selbst organisiert',
    noLabelEn: 'Self-organized',
    yesLabelDe: 'Empfehlungen bitte',
    yesLabelEn: 'Recommendations please',
  },
  {
    id: 'streetfood',
    category: 'essen',
    emoji: '🌮',
    labelDe: 'Streetfood',
    labelEn: 'Street food',
    noLabelDe: 'Eher nicht',
    noLabelEn: 'Rather not',
    yesLabelDe: 'Lecker!',
    yesLabelEn: 'Yum!',
  },
  {
    id: 'vegetarisch',
    category: 'essen',
    emoji: '🥗',
    labelDe: 'Vegetarisch / vegan',
    labelEn: 'Vegetarian / vegan',
    noLabelDe: 'Nicht relevant',
    noLabelEn: 'Not relevant',
    yesLabelDe: 'Bitte priorisieren',
    yesLabelEn: 'Please prioritize',
  },
];

export const EXPERIENCE_CATEGORY_TITLES: Record<
  ExperienceCard['category'],
  { de: string; en: string }
> = {
  wissen: { de: 'Wissen & Kultur', en: 'Knowledge & culture' },
  vibes: { de: 'Stadt-Vibes & Erlebnis', en: 'City vibes & experience' },
  mobilitaet: { de: 'Mobilität', en: 'Mobility' },
  tempo: { de: 'Tempo & Länge', en: 'Pace & length' },
  essen: { de: 'Essen & Budget', en: 'Food & budget' },
};
