/**
 * @deprecated Import from ./PromptBuilderService instead.
 * Re-export shim for backward compatibility.
 */
export {
  type FindusPersonality,
  type FindusTone,
  type OpeningHoursStatus,
  type PoiData,
  type PoiLiveContext,
  type PoiUserContext,
  type PromptBuildInput,
  type PromptStyleSettings,
  type VisitedHistory,
  type VisitedHistoryEntry,
  type YearsPreference,
  NATURAL_SPEECH_RATE_RULE,
  POI_NARRATION_SYSTEM_RULES,
  TTS_PAUSE_ENGINE_RULES,
  applyOfflinePersonalityPolish,
  buildContextAwareOfflineNarration,
  buildDynamicSystemPrompt,
  buildLiveContext,
  buildPersonalityStyleBlock,
  buildPoiContextPrompt,
  evaluateOpeningHours,
  extractKeyFactsFromPoi,
  poiWithFactsToPoiData,
  promptBuilderService,
  resolvePoiUserContext,
  resolvePromptStyleSettings,
  resolveUserInterests,
  resolveYearsPreference,
  sanitizeFactsForPrompt,
  buildEmotionalHookGuide,
  buildDeepStoryPrompt,
} from './PromptBuilderService';
