const fs=require("node:fs");
const p="C:/Users/larsf/Findus 2.0/scripts/generatePronunciationMap.mjs";
let s=fs.readFileSync(p,"utf8");
const w=(t)=>[...new Set(t.split(/[\s,]+/).map(x=>x.trim().toLowerCase()).filter(x=>x.length>1))];
function bump(name,extra){
  const re=new RegExp("const "+name+" = words\\(`([\\s\\S]*?)`\\);");
  const m=s.match(re); if(!m) return;
  const set=new Set(w(m[1]));
  for (const t of w(extra)) { if (set.size>=350) break; set.add(t); }
  s=s.replace(re,"const "+name+" = words(`"+[...set].join(" ")+"`);");
  console.log(name,set.size,set.size>=350?"OK":"SHORT");
}
bump("fillBerge","piz badile piz cengalo piz gianetti piz quattervals mont tacul mont maudit mont geant aiguille goeter aiguille chardonnet aiguille verte aiguille dru gran paradiso monte rosa east monte rosa west lyskamm north lyskamm south breithorn east breithorn west");
bump("fillAltertuemlich","vermoge mittels laengs seitens seitdem zuvor damals einstmals ehedem ehemals weiland kuenftig ferner ueberdies zudem obendrein demungeachtet desungeachtet nichtsdestotrotz alldieweil sintemal gleichfalls gleichermassen wenngleich wiewohl obschon obgleich ohnehin ohnedem ohngeachtet neulich nachmals mittlerweile inzwischen jeher jemals jenachdem mithin indes innert hiedurch hiefuer hienach hiezu hiedroben hinieden allwo allda allhier allwohin allwaerts allzeit allzu allzumal derweilen derzeit deshalben dessentwegen dieweilen eineweils einstweilen fuerwahr garwol garsehr gehabter gestalt geruhen gewahren derowegen derowyl derenthalben demnaechst fuerbass alldorten wohlweislich derhalben deswegen daher folglich dementsprechend insofern gleichwohl hingegen indessen ohnedies sodann sogleich obzwar zumal fortan hinfort hernach hierauf hierbei hierdurch hierfuer hiermit hiernach hierueber hierunter hierzu fuerderhin allbereits allenthalben allerorten allerseits allerlei allerhand demnach demzufolge dergestalt dermassen solchemnach solcherart solcherlei solchermassen solchergestalt soviel sovielmals soweit sowie sowohl zumalen zuvoerderst zumeist forthin hinfortan hernachmals hieraus hiergegen hierher hierhin hierin hierum hierzwischen");
bump("fillUmgang","abklatschen abnibbeln absahnen abstauben abwimmeln anbandeln anfixieren anmachen anquatschen anstellen aufbegehren aufdrehen aufmischen aufregen aufschneiden aufziehen ausflippen ausrasten austeilen babbeln bashen beharken bellen bruellen checken chillen clownen daddeln daherlabern deppert durchdrehen durchziehen einstecken einsammeln empfinden entspannt erledigt ey fett feiern fies fix flach flachlegen flachsen flachmachen fummeln furzen genervt genial gern gescheit gespannt gestresst gewollt glaubst gleich gluecklich grantig grinsen grummeln grundlos guenstig gurgeln gute haltung hammerhart hammergeil hartnaeckig heftig heimlich her damit herzlich heute hierhin hilflos hin und her hoffnungslos hold huepfen huellen hupen huster husten idee ignorieren illustrieren im grunde im kern im klaren im moment imstande in ordnung in sache insofern interessant irre führen irre fuehren ist doch ist egal ist klar ist schon ist so ist wahr jammeln jemand jemanden jemandem jemandes jemand jemanden jemandem jemandes");
bump("fillDialekte","achterhook borkum helgoland foeehr sylt ruhrdeutsch bergisch siegerlaender sauerlaender muensterlaender lippisch emslandplatt oldenburgplatt bremisch ruhrpott koelnisch berlinerisch hamburgerisch holsteinisch mecklenburgisch pommersch schlesisch ostpreussisch westpreussisch brandenburgisch maerkisch lausitzisch erzgebirgisch vogtlaendisch thueringisch oberlausitzisch niederlausitzisch schwaebisch fraenkisch bairisch oberpfalz niederbayern schwaben allgaeu wuerttemberg baden alemanisch allemanisch schwyzerdtsch baseldeutsch berndeutsch zuerichdeutsch stgaller luzern walliser raetoromanisch buendner oberwallis unterwallis oberengadin unterengadin muotatal leventina ticinese lombard ladin friulian venetian nordfriesisch ostfriesisch saterfriesisch low saxon low german eastphalian westphalian east prussian ruhrdeutsch koelsch berlinern hamburgerplatt holsteinisch mecklenburgisch pommersch schlesisch preussisch fraenkisch oberfraenkisch unterfraenkisch oberbayerisch niederbayerisch oberoesterreichisch niederoesterreichisch tirolerisch vorarlbergerisch kaerntnerisch steirisch burgenlaendisch wienerisch saechsisch pfaelzisch schwaebisch bayerisch oesterreichisch schweizerdeutsch gruezi mercivilmal walliser raetoromanisch norddeutsch sueddeutsch westfalen rheinisch berlinern hamburgerplatt holsteinisch mecklenburgisch pommersch schlesisch preussisch fraenkisch oberfraenkisch unterfraenkisch oberbayerisch niederbayerisch oberoesterreichisch niederoesterreichisch tirolerisch vorarlbergerisch kaerntnerisch steirisch burgenlaendisch wienerisch");
fs.writeFileSync(p,s);
