const fs=require("fs");
const p="C:/Users/larsf/Findus 2.0/scripts/generatePronunciationMap.mjs";
let s=fs.readFileSync(p,"utf8");
const w=(t)=>[...new Set(t.split(/[\s,]+/).map(x=>x.trim().toLowerCase()).filter(x=>x.length>1))];
const add={
fillAltertuemlich:"wohlweislich derhalben deswegen daher folglich dementsprechend insofern gleichwohl hingegen indessen ohnedies sodann sogleich obzwar zumal fortan hinfort hernach hierauf hierbei hierdurch hierfuer hiermit hiernach hierueber hierunter hierzu fuerwahr fuerderhin allbereits allenthalben allerorten allerseits allerlei allerhand demnach demzufolge dergestalt dermassen desungeachtet nichtsdestoweniger alldieweil sintemal gleichfalls gleichermassen wenngleich wiewohl obschon obgleich ohnehin ohnedem ohngeachtet neulich nachmals mittlerweile inzwischen jeher jemals jenachdem mithin indes innert hiedurch hiefuer hienach hiezu hiedroben hinieden allwo allda allhier allwohin allwaerts allzeit allzu allzumal derweilen derzeit deshalben dessentwegen dieweilen eineweils einstweilen garwol garsehr gehabter gestalt geruhen gewahren derowegen derowyl derenthalben demnaechst fuerbass alldorten demungeachtet nichtsdestotrotz solchemnach solcherart solcherlei solchermassen solchergestalt soviel sovielmals soweit sowie sowohl zumalen zuvoerderst zumeist forthin hinfortan hernachmals hieraus hiergegen hierher hierhin hierin hierum hierzwischen",
fillUmgang:"abgehen abziehen ankommen aufmischen auftauchen auschecken ausflippen babbeln bashen beharken blöken blöd bocken brüllen checken chillen clownen daddeln daherlabern deppert durchbrennen durchchecken durchdrehen eben echt eh eigentlich einfach eklig entspannt erledigt ey fett feiern fies fix flach flachlegen flachsen durchwinken aufmischen ausflippen babbeln bashen beharken blöken bocken brüllen checken chillen clownen daddeln deppert durchbrennen durchchecken durchdrehen eben echt eh eigentlich einfach eklig entspannt erledigt ey fett feiern fies fix flach flachlegen flachsen hammergeil hammerhart hammer krass geil mega ultra super bombig spitze klasse prima tipptopp top nice chillig relaxed easy peasy kein ding kein problem passt schon is gut is klar alles klar alles gut naja mal sehen mal gucken mal schauen irgendwie irgendwann irgendwo irgendwas irgendwer eh sowieso ohnehin sowas sowasvon voll total echt wirklich richtig absolut komplett bisschen bissl a bisserl a weng a wenig halt eben mal kurz schnell fix flott zack bumm peng knall schwuppdiwupp uff puh ui oi aha oho achso hm mhm okay alright alrighty jo ja nee nein noe doch dochmal komm schon lass mal check mal guck mal hoer mal hor mal sag mal weisst du verstehste kapiert kein plan null plan null bock kein bock voll bock mega bock null lust kein lust voll lust null stress kein stress voll stress null drama kein drama voll drama null thema kein thema voll thema null sorge kein sorge voll sorge null problem kein problem voll problem stimmt doch geht doch passt doch klar doch safe alles paletti alles roger alles astrein alles fein alles cool alles easy alles entspannt alles fit",
fillDialekte:"achterhook borkum helgoland foeehr sylt ruhrdeutsch bergisch siegerlaender sauerlaender muensterlaender lippisch emslandplatt oldenburgplatt bremisch ruhrpott koelnisch berlinerisch hamburgerisch holsteinisch mecklenburgisch pommersch schlesisch ostpreussisch westpreussisch brandenburgisch maerkisch lausitzisch erzgebirgisch vogtlaendisch thueringisch oberlausitzisch niederlausitzisch schwaebisch fraenkisch bairisch oberpfalz niederbayern schwaben allgaeu wuerttemberg baden alemanisch allemanisch schwyzerdtsch baseldeutsch bern deutsch zuerichdeutsch stgaller luzern walliser raetoromanisch buendner oberwallis unterwallis oberengadin unterengadin muotatal leventina ticinese lombard ladin friulian venetian nordfriesisch ostfriesisch saterfriesisch low saxon low german eastphalian westphalian east prussian ruhrdeutsch koelsch berlinern hamburgerplatt holsteinisch mecklenburgisch pommersch schlesisch preussisch fraenkisch oberfraenkisch unterfraenkisch oberbayerisch niederbayerisch oberoesterreichisch niederoesterreichisch tirolerisch vorarlbergerisch kaerntnerisch steirisch burgenlaendisch wienerisch sächsisch pfälzisch schwäbisch bairisch österreichisch schweizerdeutsch grüezi mercivilmal walliser rätoromanisch norddeutsch süddeutsch westfalen rheinisch berlinern hamburgerplatt holsteinisch mecklenburgisch pommersch schlesisch preussisch fränkisch oberfränkisch unterfränkisch oberbayerisch niederbayerisch oberösterreichisch niederösterreichisch tirolerisch vorarlbergerisch kärntnerisch steirisch burgenländisch wienerisch",
fillFluesse:"oderbruch spreewald havelspree dahme panke wuhle erpe recknitz trebel peene emscher lippe wupper sieg lahn fulda eder diemel leine aller oste saale unstrut whiteelster blackelster trave schwale stoer eider treene alster bille warnow peene recknitz trebel augraben havel spree dahme panke wuhle erpe mulde weisse elster schwarze elster saale unstrut white elster black elster peene warnow trave schwale stoer eider treene alster bille dove elbe suederelbe nordelbe neisse lausitzer neisse glatzer neisse inn lech iller wertach ammer amper loisach mangfall alz salzach traun enns mur drau wutach kinzig murg alb nagold enz kocher jagst rems fils aare reuss limmat thur saane rhone doubs saone loire seine marne oise aisne somme meuse saar orne touques yonne loiret cher vienne dordogne garonne lot tarn aveyron ardeche drome isere ill thur toess limmat po danube duna dunaj dunav volga dnepr dnipro don volga ural ob irtysh yenisei lena amur yangtze yellow river huang he pearl river zhujiang mekong ganges yamuna indus brahmaputra irrawaddy chao phraya red river song hong tonle sap mae nam chaophraya nile blue nile white nile congo zambezi niger senegal orange limpopo okavango mississippi missouri ohio columbia colorado rio grande amazon orinoco parana paraguay uruguay madeira tapajos negro river solimoes saint lawrence hudson delaware potomac susquehanna james river fraser river mackenzie river yukon river st lawrence seaway great lakes tigris euphrates jordan river dead sea litani wadi wadi rum wadi musa nile cataracts nile delta victoria falls zambezi gorge okavango delta chobe chobe river limpopo river orange river blue nile falls",
fillBerge:"kilimanjaro mount kenya mount meru rwenzori atlas mountains toubkal mount toubkal high atlas middle atlas anti atlas simien mountains ethiopian highlands drakensberg table mountain cape town flat top mount fuji fuji san japanese alps mount aso piz bernina piz palu piz corvatsch piz nair piz lagalb piz kesch piz ela piz daint piz sesvenna mont blanc matterhorn eiger jungfrau moench titlis pilatus rigi saentis glaernisch toedi bernina dent blanche weisshorn breithorn castor pollux liskamm dom tasschorn alphubel allalinhorn lagginhorn weissmies nadelhorn strahlhorn rimpfischhorn grossvenediger grossglockner wildspitze ortler marmolada zugspitze watzmann dachstein hochkoenig grosser arber kleiner arber schneekoppe fichtelberg brocken watzmann hochkalter tegernsee alps schliersee spitzingsee wendelstein wallberg kampenwand herzogstand heimgarten hochblassen krottenkopf hohe tauern pasterze edelweiss hochtannberg flexenpass arlberg pass reschenpass timmer joch further joch grossglockner strasse hohe tauern pass nockalmstrasse turach hohe nockberge nock mountains everest k2 kangchenjunga lhotse makalu cho oyu dhaulagiri manaslu nanga parbat annapurna gasherbrum broad peak shishapangma aconcagua ojos del salado monte bianco monte rosa dent blanche grand combin gran paradiso monte bianco cervino monte rosa massif bernese alps berner oberland jungfrau region eiger north face matterhorn zermatt mont blanc chamonix dolomites tre cime di lavaredo civetta marmolada",
fillHistorisch:"absolutismus konstitutionalismus parlamentarismus demokratie republik monarchie oligarchie aristokratie theokratie totalitarismus autoritarismus faschismus nationalsozialismus stalinismus maoismus imperialismus kolonialismus neokolonialismus globalisierung industrialisierung urbanisierung proletariat bourgeoisie adel buergerstand bauernstand zunft gilde innung handwerk manufaktur fabrik betrieb unternehmen konzern trust monopol oligopol kartell boerse aktie anleihe kredit bankrott inflation deflation rezession depression wirtschaftskrise planwirtschaft marktwirtschaft bronzezeit eisenzeit urnenfelder hallstatt kultur latene kelten germanen franken goten vandalen hunnen awaren slawen magyaren normannen wikinger kreuzfahrer steinzeit palaeolithikum mesolithikum neolithum kupferzeit frueheisenzeit hoheisenzeit voelkerwanderung merowinger karolinger ottonen salier staufer welfen askanier wittelsbacher habsburger hohenzollern kapetinger valois bourbonen romanows kriegsbeute beutezug feldzug belagerung schlacht gefecht duell tribut lehen lehnsherr vasall huldigung homagium lehenseid lehenbrief urkunde diplom siegel bull paepstliche bull kaiserurkunde koenigsurkunde landesherr territorialherr standesherr rittergut gutshof meierhof hufe hide mansus",
fillStaedte:"vilnius riga tallinn kaunas klaipeda tartu narva parnu rakvere valga voru haapsalu kuressaare paide johvi kohtlajarve split dubrovnik zagreb ljubljana bratislava kosice brno olomouc liberec pilsen ceske budejovice ostrava gdansk wroclaw poznan szczecin lodz katowice bydgoszcz lublin bialystok rzeszow koszalin kolobrzeg swinoujscie gdynia sopot malmo goteborg uppsala linkoping norrkoping helsingborg lund visby karlstad orebro vasteras eskilstuna sundsvall umea lulea kiruna tromso trondheim bergen stavanger kristiansand alesund bodo narvik lillehammer oslo drammen fredrikstad sarpsborg moss arendal grimstad kristiansand mandal flekkefjord egersund haugesund stord leirvik molde alesund ulsteinvik fusa os municipality asker baerum lorenskog ski as nesodden frogn vestby eidsvoll nannestad harestua jevnaker gran lier ringerike hole modum sigdal fla nesbyen gol al gol al hemsedal hol hol municipality uvdal numedal kongberg notodden porsgrunn skien larvik sandefjord tonsberg horten holmestrand moss sarpsborg fredrikstad halden askim mysen spydeberg trøgstad eidsberg rakkestad marker aremark indre ostfold",
};
for (const [name,extra] of Object.entries(add)){
  const re=new RegExp("const "+name+" = words\\(`([\\s\\S]*?)`\\);");
  const m=s.match(re); if(!m) continue;
  const merged=[...new Set([...w(m[1]),...w(extra)])].join(" ");
  s=s.replace(re,"const "+name+" = words(`"+merged+"`);");
}
fs.writeFileSync(p,s);
const reAll=/const (fill\w+) = words\(`([\s\S]*?)`\);/g; let m, short=[];
while((m=reAll.exec(s))){const n=w(m[2]).length; console.log(m[1],n,n>=350?"OK":"SHORT"); if(n<350)short.push(m[1]);}
console.log("short",short.length);
