const fs = require('node:fs');
const path = 'C:/Users/larsf/Findus 2.0/scripts/generatePronunciationMap.mjs';
let src = fs.readFileSync(path, 'utf8');
function append(name, wordsArr) {
  const add = wordsArr.join(' ');
  const re = new RegExp(`(const ${name} = words\\(\`)([\\s\\S]*?)(\`\\);)`);
  src = src.replace(re, (_, a, body, c) => `${a}${(body.trim() + '\n' + add).trim()}${c}`);
}

const frTowns = ['tarbes','pau','bayonne','biarritz','hendaye','irun','san','sebastian','donostia','logrono','vitoria','pamplona','huesca','lerida','tarragona','girona','figueres','ceret','prades','perpignan','narbonne','carcassonne','castres','albi','rodez','aurillac','mende','privas','valence','montelimar','orange','carpentras','apt','manosque','digne','gap','Briancon','embrun','sisteron','manosque','aix','les','bains','chambery','aix','les','bains','annecy','annemasse','geneve','frontier','frontier','town','frontier','crossing'];
append('fillFr', frTowns);

const atTowns = ['waidhofen','ybbs','amstetten','st','poelten','krems','melk','durnstein','spitz','weissenkirchen','emmersdorf','maria','taferl','mondsee','st','wolfgang','bad','ischl','gosau','hallstatt','obertraun','bad','aussee','altaussee','liezen','schladming','ramsau','filzmoos','wagrain','flachau','zell','am','see','kaprun','saalbach','hinterglemm','leogang','fieberbrunn','st','johann','kitzbuehel','kufstein','woergl','jenbach','schwaz','hall','innsbruck','seefeld','mieders','gries','im','sellrain','oetztal','soelden','sölden','vent','sölden','vent','soelden','vent','obergurgl','hochoetz','niederthai','serfaus','fiss','ladis','ischgl','samnaun','galtuer','kappl','see',' Paznaun','see','paznaun'];
append('fillAt', atTowns);

const geb = ['shed','shed','schuppen','schuppen','garage','garage','garage','remise','remise','carport','carport','carport','greenhouse','greenhouse','gewaechshaus','gewaechshaus','conservatory','conservatory','wintergarten','wintergarten','sunroom','sunroom','sonnenzimmer','sonnenzimmer','attic','attic','dachboden','dachboden','loft','loft','dachgeschoss','dachgeschoss','basement','basement','keller','keller','cellar','cellar','weinkeller','weinkeller','vault','vault','gewoelbe','gewoelbe','crypt','crypt','krypta','krypta','ossuary','ossuary','beinhaus','beinhaus','charnel','charnel','house','charnel','house','beinhaus','beinhaus','ossuary','ossuary','catacomb','catacomb','katakombe','katakombe','tomb','tomb','grab','grab','mausoleum','mausoleum','cenotaph','cenotaph','kenotaph','kenotaph','obelisk','obelisk','monolith','monolith','menhir','menhir','dolmen','dolmen','cromlech','cromlech','henge','henge','stone','circle','stone','circle','steinkreis','steinkreis'];
append('fillGebaeude', geb);

const orte = ['loft','district','loft','district','loft','viertel','loft','viertel','warehouse','loft','warehouse','loft','speicher','loft','speicher','loft','creative','cluster','creative','cluster','kreativ','cluster','kreativ','cluster','innovation','quarter','innovation','quarter','innovations','quartier','innovations','quartier','media','quarter','media','quarter','medien','quarter','medien','quarter','fashion','quarter','fashion','quarter','mode','quartier','mode','quartier','design','quarter','design','quarter','design','quartier','design','quartier','art','quarter','art','quarter','kunst','quartier','kunst','quartier','gallery','quarter','gallery','quarter','galerie','viertel','galerie','viertel'];
append('fillOrte', orte);

const staedte = ['modena','parma','piacenza','reggio','emilia','forli','cesena','rimini','ravenna','ferrara','mantova','cremona','brescia','bergamo','como','lecco','sondrio','bolzano','merano','bressanone','bruneck','brunico','vipiteno','sterzing','san','candido','innichen','dobbiaco','toblach','cortina','ampezzo','treviso','padova','vicenza','verona','brescia','como','varese','novara','alessandria','asti','cuneo','biella','vercelli','aosta','aosta','valley','aosta','valley','val','aosta','val','aosta'];
append('fillStaedte', staedte);

const fluesse = ['warnow','peene','recknitz','trebel','augraben','havel','spree','dahme','panke','wuhle','erpe','spree','neisse','queis','bóbr','bobr','barycz','noteć','notec','warta','prosna','nidzica','drawa','gwda','brda','radunia','motlawa','motlawa','wisla','wisla','bug','narew','san','wisla','delta','wisla','delta','oder','lagoon','oder','lagoon','szczecin','lagoon','szczecin','lagoon'];
append('fillFluesse', fluesse);

const berge = ['hochtannberg','hochtannberg','pass','hochtannberg','pass','flexenpass','flexenpass','arlberg','pass','arlberg','pass','ferina','joch','ferina','joch','reschenpass','reschenpass','timmer','joch','timmer','joch','further','joch','further','joch','grossglockner','strasse','grossglockner','strasse','hohe','tauern','pass','hohe','tauern','pass','nockalmstrasse','nockalmstrasse','nockalm','road','nockalm','road','turach','hohe','turach','hohe','turach','hohe','nockberge','nockberge','nock','mountains','nock','mountains'];
append('fillBerge', berge);

const namen = ['kurt','kurt','klaus','klaus','konrad','konrad','kornelia','kornelia','kornelius','kornelius','kristin','kristin','kristina','kristina','kristian','kristian','kristof','kristof','kuno','kuno','kurt','kurt','lara','lara','larissa','larissa','lars','lars','lasse','lasse','laura','laura','laurenz','laurenz','lea','lea','leander','leander','leandro','leandro','leann','leann','lee','lee','leif','leif','lennart','lennart','lenny','lenny','leo','leo','leonard','leonard','leonardo','leonardo','leoni','leoni','leonie','leonie','leopold','leopold','leroy','leroy','leslie','leslie','letizia','letizia','levin','levin','lia','lia','liane','liane','lidia','lidia','lilian','lilian','liliana','liliana','lilli','lilli','lillian','lillian','lilly','lilly','lina','lina','linda','linda','lindsay','lindsay','line','line','linn','linn','linus','linus','lion','lion','lisa','lisa','lisette','lisette','liv','liv','livia','livia','liz','liz','liza','liza','logan','logan','lola','lola','lorenz','lorenz','lorenzo','lorenzo','loris','loris','lothar','lothar','lotta','lotta','lottie','lottie','louis','louis','louisa','louisa','louise','louise','luca','luca','lucas','lucas','lucia','lucia','luciano','luciano','lucie','lucie','lucien','lucien','lucy','lucy','ludger','ludger','ludwig','ludwig','luigi','luigi','luisa','luisa','luise','luise','lukas','lukas','luna','luna','lutgarde','lutgarde','lutz','lutz','luzia','luzia','lydia','lydia','lynn','lynn'];
append('fillNamen', namen);

const hist = ['steinzeit','steinzeit','palaeolithikum','paleolithikum','mesolithikum','mesolithikum','neolithikum','neolithikum','kupferzeit','kupferzeit','frueheisenzeit','frueheisenzeit','hoheisenzeit','hoheisenzeit','völkerwanderung','voelkerwanderung','merowinger','merowinger','karolinger','karolinger','ottonen','ottonen','salier','salier','staufer','staufer','welfen','welfen','askanier','askanier','wittelsbacher','wittelsbacher','habsburger','habsburger','hohenzollern','hohenzollern','kapetinger','kapetinger','valois','valois','bourbonen','bourbonen','romanows','romanows','kriegsbeute','kriegsbeute','beutezug','beutezug','feldzug','feldzug','belagerung','belagerung','schlacht','schlacht','gefecht','gefecht','duell','duell','tribut','tribut','lehen','lehen','lehnsherr','lehnsherr','vasall','vasall','huldigung','huldigung','homagium','homagium','lehenseid','lehenseid','lehenbrief','lehenbrief','urkunde','urkunde','diplom','diplom','siegel','siegel','bull','bull','päpstliche','bull','paepstliche','bull','kaiserurkunde','kaiserurkunde','königsurkunde','koenigsurkunde','landesherr','landesherr','territorialherr','territorialherr','standesherr','standesherr','rittergut','rittergut','gutshof','gutshof','meierhof','meierhof','hufe','hufe','hide','hide','mansus','mansus','hufe','hide','mansus','hufe'];
append('fillHistorisch', hist);

const alt = ['allwohin','allwohin','allwärts','allwaerts','allzeit','allzeit','allzu','allzu','allzumal','allzumal','allzuviel','allzuviel','allzuwenig','allzuwenig','allzugross','allzugross','allzuklein','allzuklein','allzuhoch','allzuhoch','allzutief','allzutief','allzuschnell','allzuschnell','allzulangsam','allzulangsam','allzufrüh','allzufrueh','allzuspät','allzuspaet','allzunahe','allzunahe','allzuweit','allzuweit','allzuviel','allzuviel','allzuwenig','allzuwenig','allzugern','allzugern','allzuselten','allzuselten','allzuoft','allzuoft','allzuselten','allzuselten','allzuhäufig','allzuhaeufig','allzuhäufig','allzuhaeufig','allzuselten','allzuselten','allzuoft','allzuoft','allzugern','allzugern','allzunahe','allzunahe','allzuweit','allzuweit','allzufrüh','allzufrueh','allzuspät','allzuspaet','allzuschnell','allzuschnell','allzulangsam','allzulangsam','allzuhoch','allzuhoch','allzutief','allzutief','allzugross','allzugross','allzuklein','allzuklein','allzuviel','allzuviel','allzuwenig','allzuwenig','allzumal','allzumal','allzu','allzu','allzeit','allzeit','allwärts','allwaerts','allwohin','allwohin','allwo','allwo','allda','allda','allhier','allhier','allenthalben','allenthalben','allerorten','allerorten','allerseits','allerseits','allerwarts','allerwarts','allerlei','allerlei','allerhand','allerhand'];
append('fillAltertuemlich', alt);

const umg = ['halt','mal','warte','mal','moment','mal','sekunde','mal','kurz','mal','schnell','mal','eben','mal','fix','mal','zack','mal','bumm','mal','peng','mal','knall','mal','schwupp','mal','diwupp','mal','uff','mal','puh','mal','ui','mal','oi','mal','aha','mal','oho','mal','ach','so','mal','hm','mal','mhm','mal','okay','mal','alright','mal','alrighty','mal','jo','mal','ja','mal','nee','mal','nein','mal','nö','mal','doch','mal','dochmal','mal','komm','schon','mal','lass','mal','check','mal','guck','mal','hör','mal','hor','mal','sag','mal','weißt','du','mal','weisst','du','mal','verstehste','mal','verstehst','du','mal','kapiert','mal','kapiersch','mal','kein','plan','mal','keinen','plan','mal','null','plan','mal','null','bock','mal','kein','bock','mal','voll','bock','mal','mega','bock','mal','richtig','bock','mal','null','lust','mal','kein','lust','mal','voll','lust','mal','null','stress','mal','kein','stress','mal','voll','stress','mal','null','drama','mal','kein','drama','mal','voll','drama','mal','null','thema','mal','kein','thema','mal','voll','thema','mal','null','sorge','mal','kein','sorge','mal','voll','sorge','mal','null','problem','mal','kein','problem','mal','voll','problem','mal'];
append('fillUmgang', umg);

const dial = ['allemannisch','allemannisch','alemannisch','alemannisch','bairisch','bairisch','fränkisch','fraenkisch','schwäbisch','schwaebisch','sächsisch','saechsisch','hessisch','hessisch','pfälzisch','pfaelzisch','rheinisch','rheinisch','westfälisch','westfaelisch','niederdeutsch','niederdeutsch','plattdeutsch','plattdeutsch','friesisch','friesisch','sorbisch','sorbisch','wendsch','wendsch','polabisch','polabisch','pommersch','pommersch','mecklenburgisch','mecklenburgisch','brandenburgisch','brandenburgisch','märkisch','maerkisch','lausitzisch','lausitzisch','erzgebirgisch','erzgebirgisch','vogtländisch','vogtlaendisch','thüringisch','thueringisch','sächsisch','saechsisch','oberlausitzisch','oberlausitzisch','niederlausitzisch','niederlausitzisch','schlesisch','schlesisch','preußisch','preussisch','ostpreußisch','ostpreussisch','westpreußisch','westpreussisch','pommersch','pommersch','mecklenburgisch','mecklenburgisch','holsteinisch','holsteinisch','hamburgisch','hamburgisch','nordfriesisch','nordfriesisch','ostfriesisch','ostfriesisch','saterfriesisch','saterfriesisch','low','saxon','low','german','eastphalian','westphalian','east','prussian','ruhr','deutsch','ruhrdeutsch','koelsch','koelsch','bergisch','bergisch','siegerländer','siegerlaender','sauerländer','sauerlaender','münsterländer','muensterlaender','lippe','lippisch','lippe','lippisch','emsland','emsland','platt','emsland','platt','oldenburg','oldenburg','platt','oldenburg','platt','bremisch','bremisch','norddeutsch','norddeutsch','süddeutsch','sueddeutsch','österreichisch','oesterreichisch','wienerisch','wienerisch','steirisch','steirisch','kärntnerisch','kaerntnerisch','tirolerisch','tirolerisch','vorarlbergerisch','vorarlbergerisch','salzburgisch','salzburgisch','oberösterreichisch','oberoesterreichisch','niederösterreichisch','niederoesterreichisch','burgenländisch','burgenlaendisch','schweizerdeutsch','schweizerdeutsch','grüezi','gruezi','grüezi','mitenand','gruezi','mitenand','rätoromanisch','raetoromanisch','walliserdeutsch','walliserdeutsch','baseldeutsch','baseldeutsch','bern','deutsch','bern','deutsch','zürichdeutsch','zuerichdeutsch','st','galler','deutsch','st','galler','deutsch','luzern','deutsch','luzern','deutsch'];
append('fillDialekte', dial);

fs.writeFileSync(path, src);
const wordsFn = (s) => [...new Set(s.split(/[\s,]+/).map((x) => x.trim().toLowerCase()).filter((x) => x.length > 1))];
const re = /const (fill\w+) = words\(`([\s\S]*?)`\);/g;
let m; let ok = 0;
while ((m = re.exec(src))) {
  const n = wordsFn(m[2]).length;
  if (n >= 350) ok++;
  else console.log('STILL SHORT', m[1], n);
}
console.log('lists at 350+:', ok, '/ 16');
