/**
 * Hochwertige IPA-Overrides (gewinnen über generierte Kategorie-Einträge).
 * Vocab-kompatibles ɡ (U+0261).
 */
export const PRONUNCIATION_OVERRIDES: Record<string, string> = {
  // Jugendsprache & Anglizismen
  'audio guide': 'ˈɔːdiəʊ ɡaɪd',
  audioguide: 'ˈɔːdiəʊ ɡaɪd',
  'audio-guide': 'ˈɔːdiəʊ ɡaɪd',
  audioguides: 'ˈɔːdiəʊ ɡaɪdz',
  guide: 'ɡaɪd',
  guides: 'ɡaɪdz',
  cringe: 'kɹɪndʒ',
  cringy: 'ˈkɹɪndʒi',
  slay: 'sleɪ',
  slaying: 'ˈsleɪɪŋ',
  'no cap': 'noʊ kæp',
  nocap: 'noʊ kæp',
  bro: 'bɹoʊ',
  vibe: 'vaɪb',
  vibes: 'vaɪbz',
  'side eye': 'saɪd aɪ',
  sideeye: 'saɪd aɪ',
  flexen: 'ˈflɛksən',
  flex: 'flɛks',
  flexing: 'ˈflɛksɪŋ',
  match: 'mætʃ',
  matchen: 'ˈmætʃən',
  highlight: 'ˈhaɪlaɪt',
  highlights: 'ˈhaɪlaɪts',
  location: 'loʊˈkeɪʃən',
  locations: 'loʊˈkeɪʃənz',
  'check-in': 'ˈtʃekɪn',
  checkin: 'ˈtʃekɪn',
  'check-out': 'ˈtʃekaʊt',
  checkout: 'ˈtʃekaʊt',
  checkpoint: 'ˈtʃekpɔɪnt',
  viewpoint: 'ˈvjuːpɔɪnt',
  sightseeing: 'ˈsaɪtsiːɪŋ',
  lit: 'lɪt',
  based: 'beɪst',
  sus: 'sʌs',
  lowkey: 'ˈloʊkiː',
  'low-key': 'ˈloʊkiː',
  highkey: 'ˈhaɪkiː',
  'high-key': 'ˈhaɪkiː',
  ghosten: 'ˈɡoʊstən',
  ghosting: 'ˈɡoʊstɪŋ',
  rizz: 'ɹɪz',
  sigma: 'ˈsɪɡmə',
  skibidi: 'ˈskɪbɪdi',
  delulu: 'dəˈluːluː',
  goat: 'ɡoʊt',
  fomo: 'ˈfoʊmoʊ',
  yolo: 'ˈjoʊloʊ',
  cool: 'kuːl',
  okay: 'oʊˈkeɪ',
  ok: 'oʊˈkeɪ',
  chill: 'tʃɪl',
  chillen: 'ˈtʃɪlən',
  meme: 'miːm',
  viral: 'ˈvaɪɹəl',
  hashtag: 'ˈhæʃtæɡ',
  influencer: 'ˈɪnfluənsə',
  content: 'ˈkɒntent',
  streaming: 'ˈstɹiːmɪŋ',
  podcast: 'ˈpɒdkɑːst',
  playlist: 'ˈpleɪlɪst',
  selfie: 'ˈselfi',
  update: 'ˈʌpdeɪt',
  download: 'ˈdaʊnləʊd',
  upload: 'ˈʌpləʊd',
  wifi: 'ˈwaɪfaɪ',
  'wi-fi': 'ˈwaɪfaɪ',
  email: 'ˈiːmeɪl',
  smartphone: 'ˈsmɑːtfəʊn',
  laptop: 'ˈlæptɒp',
  workshop: 'ˈwɜːkʃɒp',
  briefing: 'ˈbriːfɪŋ',
  deadline: 'ˈdedlaɪn',
  feedback: 'ˈfiːdbæk',
  weekend: 'ˈwiːkend',
  lifestyle: 'ˈlaɪfstaɪl',
  meetup: 'ˈmiːtʌp',
  'meet-up': 'ˈmiːtʌp',
  startup: 'ˈstɑːtʌp',
  'start-up': 'ˈstɑːtʌp',
  coworking: 'ˈkəʊwɜːkɪŋ',
  'co-working': 'ˈkəʊwɜːkɪŋ',

  // Kulinarik / Tourismus
  tapas: 'ˈtapas',
  bruschetta: 'bʁuˈskɛta',
  gnocchi: 'ˈɲɔki',
  espresso: 'ɛsˈpʁɛso',
  paella: 'paˈeʎa',
  croissant: 'kʁwaˈsɑ̃',
  baguette: 'baˈɡɛt',
  'dim sum': 'dɪm sʌm',
  dimsum: 'dɪm sʌm',
  ramen: 'ˈɹɑːmən',
  sushi: 'ˈsuːʃi',
  risotto: 'ʁiˈzɔto',
  tiramisu: 'tiʁamiˈsu',
  prosciutto: 'pʁoˈʃuto',
  mozzarella: 'mot͡saˈʁɛla',
  pesto: 'ˈpɛsto',
  carbonara: 'kaʁboˈnaːʁa',
  bolognese: 'boloˈɲeːzə',
  lasagna: 'laˈzaːnja',
  lasagne: 'laˈzaːnjə',
  focaccia: 'foˈkattʃa',
  ciabatta: 'tʃaˈbatta',
  carpaccio: 'kaʁˈpattʃo',
  gelato: 'dʒeˈlaːto',
  macchiato: 'makˈkjaːto',
  cappuccino: 'kapuˈtʃiːno',
  latte: 'ˈlate',
  matcha: 'ˈmatʃa',
  sangria: 'saŋˈɡʁiːa',
  gazpacho: 'ɡasˈpatʃo',
  tortilla: 'toʁˈtiʎa',
  burrito: 'buˈʁito',
  taco: 'ˈtako',
  guacamole: 'ɡwakaˈmoːlə',
  chorizo: 'tʃoˈʁiːθo',
  jamón: 'xaˈmon',
  jamon: 'xaˈmon',
  pintxos: 'ˈpintʃos',
  churros: 'ˈtʃuros',
  'crème brûlée': 'kʁɛm bʁyˈle',
  'creme brulee': 'kʁɛm bʁyˈle',
  ratatouille: 'ʁatatuj',
  quiche: 'kiːʃ',
  crêpe: 'kʁɛp',
  crepe: 'kʁɛp',
  soufflé: 'suˈfle',
  'foie gras': 'fwa ɡʁɑ',
  pho: 'fɤː',
  'pad thai': 'pæd taɪ',
  kimchi: 'ˈkɪmtʃi',
  falafel: 'fəˈlɑːfəl',
  hummus: 'ˈhʊməs',
  döner: 'ˈdœnɐ',
  doner: 'ˈdœnɐ',
  gyros: 'ˈɡiːʁɔs',
  tzatziki: 'tsaˈtsiːki',
  moussaka: 'muˈsaka',
  baklava: 'ˈbaklava',
  gulasch: 'ˈɡuːlaʃ',
  schnitzel: 'ˈʃnɪtsəl',
  spätzle: 'ˈʃpɛt͡slə',
  knödel: 'ˈknøːdl̩',
  brezn: 'ˈbʁɛt͡sn̩',
  brezel: 'ˈbʁɛt͡sl̩',
  weißwurst: 'ˈvaɪsvʊʁst',
  weisswurst: 'ˈvaɪsvʊʁst',
  leberkäse: 'ˈleːbɐkɛːzə',
  obatzda: 'ˈoːbat͡sda',
  schmankerl: 'ˈʃmaŋkɐl',
  kaiserschmarrn: 'ˈkaɪzɐʃmaʁn',
  apfelstrudel: 'ˈapfl̩ʃtʁuːdl̩',
  sachertorte: 'ˈzaxɐtɔʁtə',
  tafelspitz: 'ˈtaːfl̩ʃpɪt͡s',
  currywurst: 'ˈkœʁivʊʁst',
  sauerkraut: 'ˈzaʊɐkʁaʊt',
  rösti: 'ˈʁøːsti',
  raclette: 'ʁaˈklɛt',
  fondue: 'fɔ̃ˈdy',
  prosecco: 'pʁoˈzɛko',
  champagne: 'ʃɑ̃ˈpaɲ',
  riesling: 'ˈʁiːslɪŋ',
  'grüner veltliner': 'ˈɡʁyːnɐ fɛltˈliːnɐ',
  brunch: 'bɹʌntʃ',
  smoothie: 'ˈsmuːði',
  cocktail: 'ˈkɒkteɪl',
  streetfood: 'ˈstɹiːtfuːd',
  'street food': 'ˈstɹiːt fuːd',
  restaurant: 'ʁɛstoˈʁɑ̃',
  cafe: 'ˈkæfeɪ',
  café: 'kaˈfeː',
  bistro: 'ˈbiːstroʊ',

  // Regional & Dialekte
  moin: 'moːɪn',
  'moin moin': 'moːɪn moːɪn',
  servus: 'ˈsɛʁvʊs',
  "o'zapft is": 'ɔˈt͡sapft ɪs',
  ozapftis: 'ɔˈt͡sapft ɪs',
  pfefferpotthast: 'ˈp͡fɛfɐˌpɔt.hast',
  labskaus: 'ˈlapskaʊs',
  grüezi: 'ˈɡryət͡si',
  leiwand: 'ˈlaɪvant',
  oida: 'ˈɔɪda',
  hawara: 'haˈvaːʁa',
  heuriger: 'ˈhɔʏʁɪɡɐ',
  digga: 'ˈdɪɡa',
  tschüss: 'tʃʏs',
  'grüß gott': 'ɡʁyːs ɡɔt',
  'grüss gott': 'ɡʁyːs ɡɔt',

  // Städte / Marken
  berlin: 'bɛʁˈliːn',
  hamburg: 'ˈhambʊʁk',
  münchen: 'ˈmʏnçən',
  muenchen: 'ˈmʏnçən',
  köln: 'kœln',
  koeln: 'kœln',
  frankfurt: 'ˈfʁaŋkfʊʁt',
  wien: 'viːn',
  salzburg: 'ˈzaltsbʊʁk',
  findus: 'fˈɪndʊs',
  finnus: 'fˈɪnʊs',
  begleiter: 'bəˈɡlaɪtɐ',
  anlegen: 'ˈanleːɡən',

  // Verkehr / Alltag / Ortsnamen (DE — nie engl. Bus/Holstein)
  bus: 'bˈʊs',
  buss: 'bˈʊs',
  busse: 'ˈbʊsə',
  bussen: 'ˈbʊsn̩',
  holstein: 'hˈɔlʃtaɪn',
  'schleswig-holstein': 'ˈʃleːsvɪç hˈɔlʃtaɪn',
  'schleswig holstein': 'ˈʃleːsvɪç hˈɔlʃtaɪn',
  schleswigholstein: 'ˈʃleːsvɪç hˈɔlʃtaɪn',
};
