-- Beta situation learning (also applied remotely via MCP migration beta_situation_blueprints)
-- See scripts/betaSituations.mjs for review/promote.

create table if not exists public.beta_situation_events (
  id bigint generated by default as identity primary key,
  event_id text not null unique,
  contributor_hash text not null,
  situation_key text not null,
  intent_family text not null,
  tags text[] not null default '{}'::text[],
  expect text[] not null default '{}'::text[],
  avoid text[] not null default '{}'::text[],
  summary text,
  user_type_hint jsonb not null default '{}'::jsonb,
  correction_digest text,
  prior_user_digest text,
  created_at timestamptz not null default now()
);

create table if not exists public.situation_blueprint_candidates (
  situation_key text primary key,
  intent_family text not null,
  tags text[] not null default '{}'::text[],
  expect text[] not null default '{}'::text[],
  avoid text[] not null default '{}'::text[],
  summary text,
  unique_contributors int not null default 0,
  event_count int not null default 0,
  status text not null default 'pending'
    check (status in ('pending', 'auto_ready', 'promoted', 'rejected')),
  sample_digests text[] not null default '{}'::text[],
  updated_at timestamptz not null default now(),
  promoted_at timestamptz,
  promoted_by text
);

create table if not exists public.situation_blueprints_active (
  situation_key text primary key,
  intent_family text not null,
  tags text[] not null default '{}'::text[],
  expect text[] not null default '{}'::text[],
  avoid text[] not null default '{}'::text[],
  summary text not null,
  variants jsonb not null default '[]'::jsonb,
  source text not null default 'auto_3plus',
  version int not null default 1,
  updated_at timestamptz not null default now()
);
