-- Collective learning: discovered places + signals → auto-promote at 3 unique users
-- Applied remotely as collective_learning_v1

create table if not exists public.community_discovered_places (
  place_key text primary key,
  city_hint text,
  name text not null,
  place_type text not null default 'place',
  lat double precision,
  lng double precision,
  fact_text text,
  source_url text,
  source_trust real not null default 0.4,
  contributor_hashes text[] not null default '{}'::text[],
  confirm_count int not null default 1,
  status text not null default 'pending'
    check (status in ('pending', 'active', 'rejected')),
  first_seen_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists community_discovered_places_city_idx
  on public.community_discovered_places (city_hint);
create index if not exists community_discovered_places_status_idx
  on public.community_discovered_places (status);

alter table public.community_discovered_places enable row level security;

create policy "Anon upsert community_discovered_places"
  on public.community_discovered_places for insert
  with check (true);

create policy "Anon update community_discovered_places"
  on public.community_discovered_places for update
  using (true);

create policy "Public read community_discovered_places"
  on public.community_discovered_places for select
  using (true);

create table if not exists public.community_learning_signals (
  id bigint generated by default as identity primary key,
  signal_id text not null unique,
  contributor_hash text not null,
  signal_kind text not null
    check (signal_kind in ('followup', 'error_avoid', 'cohort_style')),
  intent_family text not null default 'general',
  signal_key text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create unique index if not exists community_learning_signals_uniq_contrib
  on public.community_learning_signals (signal_key, contributor_hash);

alter table public.community_learning_signals enable row level security;

create policy "Anon insert community_learning_signals"
  on public.community_learning_signals for insert
  with check (true);

create policy "Public read community_learning_signals"
  on public.community_learning_signals for select
  using (true);

create table if not exists public.community_learning_promoted (
  signal_key text primary key,
  signal_kind text not null,
  intent_family text not null default 'general',
  payload jsonb not null default '{}'::jsonb,
  unique_contributors int not null default 0,
  source text not null default 'auto_3plus',
  version int not null default 1,
  updated_at timestamptz not null default now()
);

alter table public.community_learning_promoted enable row level security;

create policy "Public read community_learning_promoted"
  on public.community_learning_promoted for select
  using (true);

create policy "Anon upsert community_learning_promoted"
  on public.community_learning_promoted for insert
  with check (true);

create policy "Anon update community_learning_promoted"
  on public.community_learning_promoted for update
  using (true);

-- Activate place when 2+ confirms OR trust ≥ 0.55
create or replace function public.activate_discovered_place_from_row()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $$
begin
  if new.status = 'rejected' then
    return new;
  end if;
  if new.confirm_count >= 2 or new.source_trust >= 0.55 then
    new.status := 'active';
  end if;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_activate_discovered_place on public.community_discovered_places;
create trigger trg_activate_discovered_place
  before insert or update on public.community_discovered_places
  for each row execute function public.activate_discovered_place_from_row();

-- Promote signal when ≥3 unique contributors
create or replace function public.promote_learning_signal_from_row()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  contrib int;
begin
  select count(distinct contributor_hash) into contrib
  from public.community_learning_signals
  where signal_key = new.signal_key;

  if contrib >= 3 then
    insert into public.community_learning_promoted as p (
      signal_key, signal_kind, intent_family, payload,
      unique_contributors, source, version, updated_at
    ) values (
      new.signal_key, new.signal_kind, new.intent_family, new.payload,
      contrib, 'auto_3plus', 1, now()
    )
    on conflict (signal_key) do update set
      payload = excluded.payload,
      unique_contributors = greatest(p.unique_contributors, excluded.unique_contributors),
      version = p.version + 1,
      updated_at = now();
  end if;
  return new;
end;
$$;

drop trigger if exists trg_promote_learning_signal on public.community_learning_signals;
create trigger trg_promote_learning_signal
  after insert on public.community_learning_signals
  for each row execute function public.promote_learning_signal_from_row();
